In [30]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
from geopy.distance import geodesic
from scipy.signal import medfilt

def calculate_time_differences_manually(df, datetime_column='datetime', output_column='time_diff'):
    """
    Calculates the time difference (in seconds) between consecutive rows.
    """
    df[datetime_column] = pd.to_datetime(df[datetime_column])
    df = df.sort_values(datetime_column).drop_duplicates(subset=[datetime_column]).reset_index(drop=True)
    datetimes = df[datetime_column].tolist()
    time_diffs = [float('nan')]
    for i in range(1, len(datetimes)):
        delta = datetimes[i] - datetimes[i-1]
        time_diffs.append(delta.total_seconds())
    df[output_column] = time_diffs
    return df

def check_raw_gps_data(df):
    """
    Prints basic diagnostics of the raw GPS data (lat/lon differences and time diff statistics).
    """
    if not pd.api.types.is_datetime64_any_dtype(df['datetime']):
        df['datetime'] = pd.to_datetime(df['datetime'])
    else:
        print("Datetime column is already in datetime64 format; proceeding as-is.")
    
    df['lat_diff'] = df['lat'].diff().abs()
    df['lon_diff'] = df['lon'].diff().abs()
    
    print("\nFirst 20 rows with differences:")
    # Assumes that calculate_time_differences_manually() has been applied
    print(df[['datetime', 'lat_diff', 'lon_diff', 'time_diff']].iloc[:20])
    print("\nTime Difference Statistics (seconds):")
    print(df['time_diff'].describe())
    
    print("\nPotential Latitude Outliers:")
    print(df[df['lat_diff'] > df['lat_diff'].mean() + 3 * df['lat_diff'].std()][['lat', 'lat_diff', 'datetime']])
    print("\nPotential Longitude Outliers:")
    print(df[df['lon_diff'] > df['lon_diff'].mean() + 3 * df['lon_diff'].std()][['lon', 'lon_diff', 'datetime']])
    print("\nPotential Time Outliers (time differences < 0.5 sec):")
    print(df[df['time_diff'] < 0.5][['datetime', 'time_diff']])
    
    return df

def clean_trajectory(df):
    """
    Performs cleaning on a raw trajectory:
      - Checks that there are enough data points
      - Computes time differences (if not already computed)
      - Computes the next coordinates, geodesic distances, and speeds
      - Applies median filtering to speed
      - Discards trajectories with unrealistic speed profiles
      - Computes bearing and bearing changes
    """
    # Discard if too few rows
    if len(df) < 10:
        print(f"Data discarded: insufficient rows ({len(df)} rows).")
        return pd.DataFrame()
    
    # Ensure time differences are available
    if 'time_diff' not in df.columns:
        df = calculate_time_differences_manually(df)
    
    # Compute next coordinates for distance and bearing calculation
    df['next_lat'] = df['lat'].shift(-1)
    df['next_lon'] = df['lon'].shift(-1)
    
    # Calculate geodesic distance (meters) between consecutive points
    df['distance'] = df.apply(
        lambda row: geodesic((row['lat'], row['lon']), (row['next_lat'], row['next_lon'])).meters
        if pd.notna(row['next_lat']) else np.nan,
        axis=1
    )
    
    # Compute speed (m/s) and smooth using median filter (kernel size=5)
    df['speed'] = df['distance'] / df['time_diff']
    df['speed'] = medfilt(df['speed'], kernel_size=5)
    
    # Basic quality control: reject trajectories with too high mean speed
    mean_speed = df['speed'].mean()
    if mean_speed > 15:
        print(f"Data discarded: mean speed too high ({mean_speed:.2f} m/s).")
        return pd.DataFrame()
    
    # Reject trajectories where more than 50% of rows have zero speed
    zero_speed_count = (df['speed'] == 0).sum()
    if zero_speed_count > len(df) * 0.5:
        print(f"Data discarded: more than 50% of rows have zero speed ({zero_speed_count} rows).")
        return pd.DataFrame()
    
    # Compute bearing between consecutive points and the absolute change in bearing
    df['bearing'] = np.where(
        pd.notna(df['next_lat']),
        compute_bearing(df['lat'], df['lon'], df['next_lat'], df['next_lon']),
        np.nan
    )
    df['bearing_change'] = df['bearing'].diff().abs().fillna(0)
    
    print(f"Data retained: {len(df)} rows after cleaning.")
    return df

# Helper: Compute bearing (used in enrichment)
def compute_bearing(lat1, lon1, lat2, lon2):
    """
    Compute bearing between two GPS coordinates.
    """
    dlon = np.radians(lon2 - lon1)
    lat1, lat2 = np.radians(lat1), np.radians(lat2)
    y = np.sin(dlon) * np.cos(lat2)
    x = np.cos(lat1) * np.sin(lat2) - np.sin(lat1) * np.cos(lat2) * np.cos(dlon)
    return np.degrees(np.arctan2(y, x)) % 360

In [35]:
from geopy.geocoders import Nominatim

def get_location_name(lat, lon):
    """
    Enriches a GPS coordinate by retrieving a human-readable location name.
    """
    geolocator = Nominatim(user_agent="geoenrichment")
    try:
        location = geolocator.reverse((lat, lon), exactly_one=True)
        return location.address
    except Exception as e:
        return "Unknown Location"

def minimal_angle_diff(diff):
    """Compute the minimal absolute difference between two angles (in degrees)."""
    diff = abs(diff) % 360
    return diff if diff <= 180 else 360 - diff

def compute_enriched_metrics(df):
    """
    Computes enriched trip metrics:
      - Step distances and overall distance (km)
      - Raw speeds with mode-based speed capping and outlier filtering
      - Acceleration (m/s²)
      - Turning metrics (bearing change, turn rate, etc.)
    """
    # Ensure time differences are available
    if 'time_diff' not in df.columns:
        df = calculate_time_differences_manually(df)
    
    # Compute next coordinates and step distance
    df['next_lat'] = df['lat'].shift(-1)
    df['next_lon'] = df['lon'].shift(-1)
    df = df.dropna(subset=['lat', 'lon', 'next_lat', 'next_lon'])
    df['step_distance'] = df.apply(
        lambda row: geodesic((row['lat'], row['lon']), (row['next_lat'], row['next_lon'])).meters,
        axis=1
    )
    total_distance = df['step_distance'].sum() / 1000  # in km
    
    # Compute raw speed (m/s)
    df['speed'] = df['step_distance'] / df['time_diff']
    
    # Apply mode-based speed cap
    if 'transport_mode' in df.columns and not df['transport_mode'].isna().all():
        mode = df['transport_mode'].mode()[0] if not df['transport_mode'].mode().empty else 'unknown'
    else:
        mode = 'unknown'
    
    speed_cap_mps = {
        'walk': 2.78,  # 10 km/h
        'bike': 6.94,  # 25 km/h
        'bus': 11.11,  # 40 km/h
        'car': 13.89,  # 50 km/h
        'taxi': 13.89, # 50 km/h
        'unknown': 13.89
    }.get(mode.lower(), 6.94)  # Default cap
    
    accel_cap_mps2 = {
        'walk': 2.0,
        'bike': 3.0,
        'bus': 3.5,
        'car': 4.0,
        'taxi': 4.0,
        'unknown': 4.0
    }.get(mode.lower(), 4.0)
    
    # Outlier filtering using the IQR method:
    original_speed = df['speed'].copy()
    # Outlier filtering using the IQR method
    Q1 = df['speed'].quantile(0.25)
    Q3 = df['speed'].quantile(0.75)
    IQR = Q3 - Q1
    upper_bound = Q3 + 1.5 * IQR

    # Use the lower cap between the IQR upper bound and the mode-based cap
    final_speed_cap = min(upper_bound, speed_cap_mps)
    
    # Count the number of speed outliers before clipping
    outlier_count = (original_speed > final_speed_cap).sum()
    print("Outlier count before clipping:", outlier_count)
    
    df['speed'] = df['speed'].clip(upper=final_speed_cap)
    df['speed'] = df['speed'].clip(upper=speed_cap_mps)
    
    # Smooth speed with a median filter
    df['speed'] = medfilt(df['speed'], kernel_size=5)
    df['speed_kmh'] = df['speed'] * 3.6  # Convert m/s to km/h
    
    # Compute acceleration (m/s²)
    df['acceleration'] = df['speed'].diff() / df['time_diff']
    df['acceleration'] = df['acceleration'].fillna(0)
    
    # # Cap acceleration (if already computed) and speed
    # if 'acceleration' in df.columns:
    #     df['acceleration'] = df['acceleration'].clip(upper=accel_cap_mps2)

    # Turning metrics: Compute bearing and its change using circular difference
    df['bearing'] = df.apply(
        lambda row: compute_bearing(row['lat'], row['lon'], row['next_lat'], row['next_lon']),
        axis=1
    )

    # Use the minimal angle difference to calculate bearing changes
    df['bearing_change'] = df['bearing'].diff().apply(minimal_angle_diff)

    turn_threshold = 30  # degrees
    num_turns = (df['bearing_change'] >= turn_threshold).sum()
    duration_minutes = df['time_diff'].sum() / 60
    turn_rate = num_turns / duration_minutes if duration_minutes > 0 else 0
    avg_turn_angle = df['bearing_change'].mean()
    turn_angle_std = df['bearing_change'].std()
    
    metrics = {
        "total_distance": total_distance,
        "max_speed": df['speed_kmh'].max(),
        "min_speed": df['speed_kmh'].min(),
        "speed_std": df['speed_kmh'].std(),
        "avg_speed": df['speed_kmh'].mean(),
        "avg_acceleration": df['acceleration'].mean(),
        "max_acceleration": df['acceleration'].max(),
        "acceleration_std": df['acceleration'].std(),
        "num_turns": int(num_turns),
        "turn_rate": turn_rate,
        "avg_turn_angle": avg_turn_angle,
        "turn_angle_std": turn_angle_std,
        "avg_bearing_change": avg_turn_angle
    }
    return metrics

def generate_trip_description(df, metrics):
    """
    Generates a human-readable summary of the trip using enriched metrics.
    Also enriches the trip by retrieving start and end location names.
    """
    if df.empty:
        return "No valid data for this trip.", "Unknown"
    
    start = df.iloc[0]
    end = df.iloc[-1]
    
    start_location = get_location_name(start['lat'], start['lon'])
    end_location = get_location_name(end['lat'], end['lon'])
    
    if 'transport_mode' in df.columns and not df['transport_mode'].isna().all():
        mode_series = df['transport_mode']
        mode_value = mode_series.mode()[0]
        mode_count = (mode_series == mode_value).sum()
        total_points = len(mode_series)
        threshold = 0.6
        if (mode_count / total_points) >= threshold:
            transport_mode = mode_value
        else:
            transport_mode = "Mixed"
    else:
        transport_mode = "Unknown"
    
    description = f"""
Trip Summary:
- Start: {start['datetime'].strftime('%Y-%m-%d %H:%M:%S')} at {start_location}
- End: {end['datetime'].strftime('%Y-%m-%d %H:%M:%S')} at {end_location}
- Duration: {(end['datetime'] - start['datetime'])}
- Distance: {metrics['total_distance']:.2f} km
- Average Speed: {metrics['avg_speed']:.2f} km/h
- Average Bearing Change: {metrics['avg_bearing_change']:.2f}°
- Max Speed: {metrics['max_speed']:.2f} km/h
- Min Speed: {metrics['min_speed']:.2f} km/h
- Speed Variability: {metrics['speed_std']:.2f} km/h
- Average Acceleration: {metrics['avg_acceleration']:.2f} m/s²
- Max Acceleration: {metrics['max_acceleration']:.2f} m/s²
- Number of Turns: {metrics['num_turns']}
- Turn Rate: {metrics['turn_rate']:.2f} turns/min
- Average Turn Angle: {metrics['avg_turn_angle']:.2f}°
- Turn Angle Variability: {metrics['turn_angle_std']:.2f}°
- Transport Mode: {transport_mode}
    """
    
    # # Optionally, write the summary to a file.
    # with open("trip_summaries.txt", "a", encoding="utf-8") as f:
    #     f.write(description + "\n\n")
    
    return description, transport_mode

In [36]:
import os
import glob
import geopandas as gpd
import pandas as pd
import warnings
from geopy.distance import geodesic
from scipy.signal import medfilt
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

# Folder where the cleaned sub-trajectories are stored.
folder_path = "Sub_Trajectories_Cleaned"
geojson_files = glob.glob(os.path.join(folder_path, "**/*.geojson"), recursive=True)
print(f"Number of GeoJSON files found: {len(geojson_files)}")

# Initialize accumulators for global analysis
total_rows_global = 0
extreme_outlier_rows_global = 0
very_extreme_outlier_rows_global = 0
regular_capped_rows_global = 0

# List to store trip-level metrics
trip_data = []
# counter = 0
for file in geojson_files:
    try:
        # counter += 1
        # if counter == 20:
        #     break
        # Read the file into a GeoDataFrame.
        gdf = gpd.read_file(file)
        if gdf.empty:
            print(f"File {file} is empty. Skipping.")
            continue

        # Clean the trajectory using your function.
        gdf_clean = clean_trajectory(gdf)
        if gdf_clean.empty:
            print(f"File {file} did not pass cleaning. Skipping.")
            continue

        # Ensure time differences are computed.
        gdf_clean = calculate_time_differences_manually(gdf_clean)
        if not pd.api.types.is_datetime64_any_dtype(gdf_clean['datetime']):
            gdf_clean['datetime'] = pd.to_datetime(gdf_clean['datetime'])
        gdf_clean = gdf_clean.sort_values('datetime').reset_index(drop=True)

        # Compute necessary step distances for speed calculation
        gdf_clean['next_lat'] = gdf_clean['lat'].shift(-1)
        gdf_clean['next_lon'] = gdf_clean['lon'].shift(-1)
        gdf_clean = gdf_clean.dropna(subset=['lat', 'lon', 'next_lat', 'next_lon'])
        gdf_clean['step_distance'] = gdf_clean.apply(
            lambda row: geodesic((row['lat'], row['lon']), (row['next_lat'], row['next_lon'])).meters,
            axis=1
        )
        
        # Compute raw speeds
        gdf_clean['speed'] = gdf_clean['step_distance'] / gdf_clean['time_diff']

        # Determine mode for capping
        if 'transport_mode' in gdf_clean.columns and not gdf_clean['transport_mode'].isna().all():
            mode = gdf_clean['transport_mode'].mode()[0] if not gdf_clean['transport_mode'].mode().empty else 'unknown'
        else:
            mode = 'unknown'
        
        # Compute the maximum speed for the trip
        trip_max_speed = gdf_clean['speed'].max()
            
        speed_cap_mps = {
            'walk': 2.78,   # 10 km/h
            'bike': 6.94,   # 25 km/h
            'bus': 11.11,   # 40 km/h
            'car': 13.89,   # 50 km/h
            'taxi': 13.89,  # 50 km/h
            'unknown': 13.89
        }.get(mode.lower(), 6.94)

        # Check if the trip's maximum speed exceeds the mode-based cap
        if trip_max_speed >= speed_cap_mps:
            print(f"Trip max speed ({trip_max_speed:.2f} m/s) exceeds the cap of {speed_cap_mps:.2f} m/s.")
        else:
            print(f"Trip max speed ({trip_max_speed:.2f} m/s) is within the cap of {speed_cap_mps:.2f} m/s.")

        # Calculate rows counts before filtering
        initial_rows = len(gdf_clean)
        
        # Count extreme outliers (speed > 2x cap)
        extreme_outliers = (gdf_clean['speed'] > 2 * speed_cap_mps).sum()
        extreme_outlier_rows_global += extreme_outliers
        
        # Count very extreme outliers (speed > 5x cap)
        very_extreme_outliers = (gdf_clean['speed'] > 5 * speed_cap_mps).sum()
        very_extreme_outlier_rows_global += very_extreme_outliers
        
        # Count regular capped points (cap < speed <= 2*cap)
        regular_capped = ((gdf_clean['speed'] > speed_cap_mps) & (gdf_clean['speed'] <= 2 * speed_cap_mps)).sum()
        regular_capped_rows_global += regular_capped
        
        print(f"Initial rows: {initial_rows}")
        print(f"Speed cap: {speed_cap_mps}")
        print(f"Regular capped (cap < speed <= 2x cap): {regular_capped}")
        print(f"Extreme outliers (>2x cap): {extreme_outliers}")
        print(f"Very extreme outliers (>5x cap): {very_extreme_outliers}")
        
        # REMOVE extreme outliers (speed > 2x cap)
        gdf_clean = gdf_clean[gdf_clean['speed'] <= 2 * speed_cap_mps].copy()
        
        # Apply capping for the remaining rows that exceed cap but aren't extreme
        gdf_clean['speed'] = gdf_clean['speed'].clip(upper=speed_cap_mps)
        
        # Update global counter for total rows (after removal)
        total_rows_global += len(gdf_clean)
        
        print(f"Rows after removal: {len(gdf_clean)}")
        print(f"Points removed: {initial_rows - len(gdf_clean)}")
        print(f"Total rows processed globally: {total_rows_global}")

        # Compute enriched metrics (this will perform the capping inside the function)
        metrics = compute_enriched_metrics(gdf_clean)
        if metrics is None:
            print(f"Metrics could not be computed for file {file}. Skipping.")
            continue

        # Calculate additional trip-level information.
        if len(gdf_clean) > 0:  # Check if we still have points after removal
            start_time = gdf_clean['datetime'].iloc[0]
            end_time = gdf_clean['datetime'].iloc[-1]
            duration_sec = (end_time - start_time).total_seconds()

            if 'transport_mode' in gdf_clean.columns:
                mode_series = gdf_clean['transport_mode'].dropna()
                if len(mode_series.unique()) == 1:
                    trip_mode = mode_series.iloc[0]
                else:
                    trip_mode = mode_series.mode()[0]
            else:
                trip_mode = "Unknown"

            summary, _ = generate_trip_description(gdf_clean, metrics)

            # Append additional information to metrics.
            metrics['trip_id'] = os.path.basename(file)
            metrics['start_time'] = start_time
            metrics['end_time'] = end_time
            metrics['duration_sec'] = duration_sec
            metrics['transport_mode'] = trip_mode
            
            # Add outlier info to the metrics
            metrics['initial_points'] = initial_rows
            metrics['points_removed'] = initial_rows - len(gdf_clean)
            metrics['pct_points_removed'] = ((initial_rows - len(gdf_clean)) / initial_rows) * 100 if initial_rows > 0 else 0
            metrics['regular_capped_points'] = regular_capped
            metrics['extreme_outliers_removed'] = extreme_outliers
            metrics['speed_cap'] = speed_cap_mps
            
            metrics['trip_summary'] = summary

            trip_data.append(metrics)

    except Exception as e:
        print(f"Error processing file {file}: {e}")

# Create a DataFrame from the aggregated trip metrics.
df_trip_level = pd.DataFrame(trip_data)
print("Trip-level dataset shape:", df_trip_level.shape)
display(df_trip_level.head())

# Save the aggregated trip-level dataset to CSV.
output_csv = "trip_level_data.csv"
df_trip_level.to_csv(output_csv, index=False)
print(f"Trip-level data saved to '{output_csv}'.")

# Compute global percentages
total_initial_rows = total_rows_global + extreme_outlier_rows_global
if total_initial_rows > 0:
    pct_extreme_outliers_global = (extreme_outlier_rows_global / total_initial_rows) * 100
    pct_very_extreme_outliers_global = (very_extreme_outlier_rows_global / total_initial_rows) * 100
    pct_regular_capped_global = (regular_capped_rows_global / total_initial_rows) * 100
else:
    pct_extreme_outliers_global = 0
    pct_very_extreme_outliers_global = 0
    pct_regular_capped_global = 0

# Write the analysis to a text file in the ML_result folder.
output_analysis_path = os.path.join("ML_result", "capping_analysis.txt")
os.makedirs(os.path.dirname(output_analysis_path), exist_ok=True)  # Ensure the folder exists

with open(output_analysis_path, "w") as f:
    f.write("Global Cleaning Analysis\n")
    f.write("=======================\n")
    f.write(f"Total initial rows: {total_initial_rows}\n")
    f.write(f"Extreme outliers removed (>2x cap): {extreme_outlier_rows_global}\n")
    f.write(f"Percentage of extreme outliers removed: {pct_extreme_outliers_global:.2f}%\n")
    f.write(f"Very extreme outliers subset (>5x cap): {very_extreme_outlier_rows_global}\n")
    f.write(f"Percentage of very extreme outliers: {pct_very_extreme_outliers_global:.2f}%\n\n")
    
    f.write("Remaining Data Analysis\n")
    f.write("=======================\n")
    f.write(f"Total rows after removal: {total_rows_global}\n")
    f.write(f"Rows with speed capped (speed > cap but ≤ 2x cap): {regular_capped_rows_global}\n")
    f.write(f"Percentage of rows capped: {pct_regular_capped_global:.2f}%\n")

print(f"Enhanced cleaning analysis saved to '{output_analysis_path}'.")

Skipping field time: unsupported OGR type: 10

Number of GeoJSON files found: 1092
Data retained: 10 rows after cleaning.
Trip max speed (2.86 m/s) is within the cap of 6.94 m/s.
Initial rows: 9
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 8
Points removed: 1
Total rows processed globally: 8
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 825 rows after cleaning.
Trip max speed (54.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 824
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 28
Very extreme outliers (>5x cap): 8
Rows after removal: 795
Points removed: 29
Total rows processed globally: 803
Outlier count before clipping: 52

Skipping field time: unsupported OGR type: 10

Data retained: 24 rows after cleaning.
Trip max speed (11.61 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 23
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 22
Points removed: 1
Total rows processed globally: 825
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (2.10 m/s) is within the cap of 2.78 m/s.
Initial rows: 15
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 14
Points removed: 1
Total rows processed globally: 839
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 187 rows after cleaning.
Trip max speed (26.13 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 186
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 181
Points removed: 5
Total rows processed globally: 1020
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 209 rows after cleaning.
Trip max speed (63.18 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 208
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 204
Points removed: 4
Total rows processed globally: 1224
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 485 rows after cleaning.
Trip max speed (50.42 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 484
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 212
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 477
Points removed: 7
Total rows processed globally: 1701
Outlier count before clipping: 215

Skipping field time: unsupported OGR type: 10

Data retained: 224 rows after cleaning.
Trip max speed (4005.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 223
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 216
Points removed: 7
Total rows processed globally: 1917
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 69 rows after cleaning.
Trip max speed (26.64 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 68
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 66
Points removed: 2
Total rows processed globally: 1983
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 295 rows after cleaning.
Trip max speed (48.35 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 294
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 53
Extreme outliers (>2x cap): 158
Very extreme outliers (>5x cap): 15
Rows after removal: 135
Points removed: 159
Total rows processed globally: 2118
Outlier count before clipping: 54

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (66.87 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 27
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 23
Points removed: 4
Total rows processed globally: 2141
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (5.31 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 45
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 44
Points removed: 1
Total rows processed globally: 2185
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 812 rows after cleaning.
Trip max speed (34.95 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 811
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 803
Points removed: 8
Total rows processed globally: 2988
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 88 rows after cleaning.
Trip max speed (13.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 87
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 84
Points removed: 3
Total rows processed globally: 3072
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (11.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 19
Points removed: 2
Total rows processed globally: 3091
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 349 rows after cleaning.
Trip max speed (57.05 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 348
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 339
Points removed: 9
Total rows processed globally: 3430
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (7.21 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 53
Points removed: 5
Total rows processed globally: 3483
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 477 rows after cleaning.
Trip max speed (108.79 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 476
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 6
Rows after removal: 451
Points removed: 25
Total rows processed globally: 3934
Outlier count before clipping: 41

Skipping field time: unsupported OGR type: 10

Data retained: 662 rows after cleaning.
Trip max speed (80.97 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 661
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 64
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 655
Points removed: 6
Total rows processed globally: 4589
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10

Data retained: 220 rows after cleaning.
Trip max speed (2110.20 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 219
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 213
Points removed: 6
Total rows processed globally: 4802
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 420 rows after cleaning.
Trip max speed (59.11 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 419
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 33
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 415
Points removed: 4
Total rows processed globally: 5217
Outlier count before clipping: 34

Skipping field time: unsupported OGR type: 10

Data retained: 96 rows after cleaning.
Trip max speed (37.25 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 95
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 28
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 88
Points removed: 7
Total rows processed globally: 5305
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 407 rows after cleaning.
Trip max speed (41.50 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 406
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 45
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 398
Points removed: 8
Total rows processed globally: 5703
Outlier count before clipping: 47

Skipping field time: unsupported OGR type: 10

Data retained: 109 rows after cleaning.
Trip max speed (27.28 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 108
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 102
Points removed: 6
Total rows processed globally: 5805
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 416 rows after cleaning.
Trip max speed (55.97 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 415
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 400
Points removed: 15
Total rows processed globally: 6205
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 241 rows after cleaning.
Trip max speed (127.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 240
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 4
Rows after removal: 232
Points removed: 8
Total rows processed globally: 6437
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 112 rows after cleaning.
Trip max speed (88.90 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 111
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 5
Rows after removal: 89
Points removed: 22
Total rows processed globally: 6526
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 196 rows after cleaning.
Trip max speed (19.27 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 195
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 190
Points removed: 5
Total rows processed globally: 6716
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 322 rows after cleaning.
Trip max speed (49.23 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 321
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 80
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 314
Points removed: 7
Total rows processed globally: 7030
Outlier count before clipping: 84

Skipping field time: unsupported OGR type: 10

Data retained: 161 rows after cleaning.
Trip max speed (21.79 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 160
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 157
Points removed: 3
Total rows processed globally: 7187
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 84 rows after cleaning.
Trip max speed (482.84 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 83
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 78
Points removed: 5
Total rows processed globally: 7265
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 173 rows after cleaning.
Trip max speed (18.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 172
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 41
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 166
Points removed: 6
Total rows processed globally: 7431
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20080405033014/walk_cleaned.geojson did not pass cleaning. Skipping.
Data discarded: mean speed too high (17.17 m/s).
File Sub_Trajectories_Cleaned/20090917000404/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 78 rows after cleaning.
Trip max speed (5211.26 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 77
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 75
Points removed: 2
Total rows processed globally: 7506
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 415 rows after cleaning.
Trip max speed (33.59 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 414
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 409
Points removed: 5
Total rows processed globally: 7915
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 57 rows after cleaning.
Trip max speed (25.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 56
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 51
Points removed: 5
Total rows processed globally: 7966
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 111 rows after cleaning.
Trip max speed (85.18 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 110
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 107
Points removed: 3
Total rows processed globally: 8073
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 812 rows after cleaning.
Trip max speed (76.60 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 811
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 40
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 1
Rows after removal: 791
Points removed: 20
Total rows processed globally: 8864
Outlier count before clipping: 57

Skipping field time: unsupported OGR type: 10

Data retained: 95 rows after cleaning.
Trip max speed (139.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 94
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 91
Points removed: 3
Total rows processed globally: 8955
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 613 rows after cleaning.
Trip max speed (234.70 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 612
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 4
Rows after removal: 592
Points removed: 20
Total rows processed globally: 9547
Outlier count before clipping: 44

Skipping field time: unsupported OGR type: 10

Data retained: 181 rows after cleaning.
Trip max speed (20.99 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 180
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 168
Points removed: 12
Total rows processed globally: 9715
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 1097 rows after cleaning.
Trip max speed (54.52 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1096
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 1091
Points removed: 5
Total rows processed globally: 10806
Outlier count before clipping: 34

Skipping field time: unsupported OGR type: 10

Data retained: 26 rows after cleaning.
Trip max speed (16.76 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 25
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 22
Points removed: 3
Total rows processed globally: 10828
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 542 rows after cleaning.
Trip max speed (189.43 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 541
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 534
Points removed: 7
Total rows processed globally: 11362
Outlier count before clipping: 50

Skipping field time: unsupported OGR type: 10

Data retained: 53 rows after cleaning.
Trip max speed (9.23 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 52
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 49
Points removed: 3
Total rows processed globally: 11411
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 400 rows after cleaning.
Trip max speed (90.07 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 399
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 3
Rows after removal: 387
Points removed: 12
Total rows processed globally: 11798
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 333 rows after cleaning.
Trip max speed (58.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 332
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 327
Points removed: 5
Total rows processed globally: 12125
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 25 rows after cleaning.
Trip max speed (47.58 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 24
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 8
Total rows processed globally: 12141
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 131 rows after cleaning.
Trip max speed (76.09 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 130
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 125
Points removed: 5
Total rows processed globally: 12266
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (6.20 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 15
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 12
Points removed: 3
Total rows processed globally: 12278
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 616 rows after cleaning.
Trip max speed (44.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 615
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 613
Points removed: 2
Total rows processed globally: 12891
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (2.45 m/s) is within the cap of 2.78 m/s.
Initial rows: 12
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 12902
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 1221 rows after cleaning.
Trip max speed (101.84 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1220
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 111
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 1205
Points removed: 15
Total rows processed globally: 14107
Outlier count before clipping: 121

Skipping field time: unsupported OGR type: 10

Data retained: 607 rows after cleaning.
Trip max speed (171.78 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 606
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 263
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 603
Points removed: 3
Total rows processed globally: 14710
Outlier count before clipping: 265

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (29.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 92
Points removed: 6
Total rows processed globally: 14802
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 170 rows after cleaning.
Trip max speed (33.36 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 169
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 164
Points removed: 5
Total rows processed globally: 14966
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 52 rows after cleaning.
Trip max speed (21.10 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 51
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 50
Points removed: 1
Total rows processed globally: 15016
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (12.74 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 54
Points removed: 4
Total rows processed globally: 15070
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 389 rows after cleaning.
Trip max speed (285.72 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 388
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 2
Rows after removal: 374
Points removed: 14
Total rows processed globally: 15444
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 883 rows after cleaning.
Trip max speed (224.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 882
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 264
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 872
Points removed: 10
Total rows processed globally: 16316
Outlier count before clipping: 269

Skipping field time: unsupported OGR type: 10

Data retained: 694 rows after cleaning.
Trip max speed (113.09 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 693
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 342
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 3
Rows after removal: 675
Points removed: 18
Total rows processed globally: 16991
Outlier count before clipping: 347

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (5.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 1
Total rows processed globally: 17011
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20080918235405/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 1410 rows after cleaning.
Trip max speed (66.26 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1409
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 110
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 2
Rows after removal: 1388
Points removed: 21
Total rows processed globally: 18399
Outlier count before clipping: 126

Skipping field time: unsupported OGR type: 10

Data retained: 520 rows after cleaning.
Trip max speed (24.35 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 519
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 508
Points removed: 11
Total rows processed globally: 18907
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 195 rows after cleaning.
Trip max speed (20.16 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 194
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 192
Points removed: 2
Total rows processed globally: 19099
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 1192 rows after cleaning.
Trip max speed (50.88 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1191
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 0
Rows after removal: 1177
Points removed: 14
Total rows processed globally: 20276
Outlier count before clipping: 45

Skipping field time: unsupported OGR type: 10

Data retained: 246 rows after cleaning.
Trip max speed (36.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 245
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 237
Points removed: 8
Total rows processed globally: 20513
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 88 rows after cleaning.
Trip max speed (15.01 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 87
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 85
Points removed: 2
Total rows processed globally: 20598
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (1.82 m/s) is within the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 1
Total rows processed globally: 20618
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (18.02 m/s).
File Sub_Trajectories_Cleaned/20090928104328/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 27 rows after cleaning.
Trip max speed (6.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 26
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 23
Points removed: 3
Total rows processed globally: 20641
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 506 rows after cleaning.
Trip max speed (60.51 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 505
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 493
Points removed: 12
Total rows processed globally: 21134
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 165 rows after cleaning.
Trip max speed (25.32 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 164
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 63
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 163
Points removed: 1
Total rows processed globally: 21297
Outlier count before clipping: 63

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (10.23 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 15
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 13
Points removed: 2
Total rows processed globally: 21310
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.35 m/s).
File Sub_Trajectories_Cleaned/20090522105319/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 84 rows after cleaning.
Trip max speed (17.42 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 83
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 82
Points removed: 1
Total rows processed globally: 21392
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 697 rows after cleaning.
Trip max speed (11.68 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 696
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 0
Rows after removal: 684
Points removed: 12
Total rows processed globally: 22076
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10

Data retained: 364 rows after cleaning.
Trip max speed (47.73 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 363
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 353
Points removed: 10
Total rows processed globally: 22429
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 1523 rows after cleaning.
Trip max speed (57.52 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1522
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 146
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 1
Rows after removal: 1500
Points removed: 22
Total rows processed globally: 23929
Outlier count before clipping: 163

Skipping field time: unsupported OGR type: 10

Data retained: 286 rows after cleaning.
Trip max speed (15.82 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 285
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 279
Points removed: 6
Total rows processed globally: 24208
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.71 m/s).
File Sub_Trajectories_Cleaned/20090703082122/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 28 rows after cleaning.
Trip max speed (4.04 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 27
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 26
Points removed: 1
Total rows processed globally: 24234
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 14 rows after cleaning.
Trip max speed (3.98 m/s) is within the cap of 6.94 m/s.
Initial rows: 13
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 12
Points removed: 1
Total rows processed globally: 24246
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 419 rows after cleaning.
Trip max speed (27.54 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 418
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 59
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 417
Points removed: 1
Total rows processed globally: 24663
Outlier count before clipping: 59

Skipping field time: unsupported OGR type: 10

Data retained: 108 rows after cleaning.
Trip max speed (18.11 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 107
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 103
Points removed: 4
Total rows processed globally: 24766
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 60 rows after cleaning.
Trip max speed (30.23 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 59
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 57
Points removed: 2
Total rows processed globally: 24823
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 58 rows after cleaning.
Trip max speed (7.21 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 57
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 55
Points removed: 2
Total rows processed globally: 24878
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 14 rows after cleaning.
Trip max speed (78.12 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 13
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 11
Points removed: 2
Total rows processed globally: 24889
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (8.29 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 18
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 2
Total rows processed globally: 24905
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 319 rows after cleaning.
Trip max speed (32.95 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 318
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 314
Points removed: 4
Total rows processed globally: 25219
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (6.88 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 61
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 59
Points removed: 2
Total rows processed globally: 25278
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 357 rows after cleaning.
Trip max speed (61.22 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 356
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 53
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 352
Points removed: 4
Total rows processed globally: 25630
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 1631 rows after cleaning.
Trip max speed (83.19 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1630
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 181
Extreme outliers (>2x cap): 348
Very extreme outliers (>5x cap): 63
Rows after removal: 1281
Points removed: 349
Total rows processed globally: 26911
Outlier count before clipping: 251

Skipping field time: unsupported OGR type: 10

Data retained: 543 rows after cleaning.
Trip max speed (87.02 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 542
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 32
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 533
Points removed: 9
Total rows processed globally: 27444
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 37 rows after cleaning.
Trip max speed (3.83 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 36
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 35
Points removed: 1
Total rows processed globally: 27479
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 362 rows after cleaning.
Trip max speed (65.79 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 361
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 359
Points removed: 2
Total rows processed globally: 27838
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 3131 rows after cleaning.
Trip max speed (1067.07 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 3130
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 780
Extreme outliers (>2x cap): 2277
Very extreme outliers (>5x cap): 48
Rows after removal: 852
Points removed: 2278
Total rows processed globally: 28690
Outlier count before clipping: 810

Skipping field time: unsupported OGR type: 10

Data retained: 411 rows after cleaning.
Trip max speed (7.98 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 410
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 403
Points removed: 7
Total rows processed globally: 29093
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 468 rows after cleaning.
Trip max speed (93.98 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 467
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 37
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 3
Rows after removal: 454
Points removed: 13
Total rows processed globally: 29547
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20070424124908/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 55 rows after cleaning.
Trip max speed (10.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 54
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 51
Points removed: 3
Total rows processed globally: 29598
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (18.43 m/s).
File Sub_Trajectories_Cleaned/20090912064500/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 82 rows after cleaning.
Trip max speed (159.67 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 81
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 75
Points removed: 6
Total rows processed globally: 29673
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 53 rows after cleaning.
Trip max speed (4.89 m/s) is within the cap of 6.94 m/s.
Initial rows: 52
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 51
Points removed: 1
Total rows processed globally: 29724
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 40 rows after cleaning.
Trip max speed (16.08 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 39
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 38
Points removed: 1
Total rows processed globally: 29762
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 268 rows after cleaning.
Trip max speed (50.05 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 267
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 260
Points removed: 7
Total rows processed globally: 30022
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 41 rows after cleaning.
Trip max speed (50.86 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 40
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 1
Rows after removal: 21
Points removed: 19
Total rows processed globally: 30043
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 785 rows after cleaning.
Trip max speed (203.00 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 784
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 777
Points removed: 7
Total rows processed globally: 30820
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 1335 rows after cleaning.
Trip max speed (1038.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1334
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 107
Extreme outliers (>2x cap): 57
Very extreme outliers (>5x cap): 26
Rows after removal: 1276
Points removed: 58
Total rows processed globally: 32096
Outlier count before clipping: 142

Skipping field time: unsupported OGR type: 10

Data retained: 368 rows after cleaning.
Trip max speed (55.99 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 367
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 28
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 2
Rows after removal: 351
Points removed: 16
Total rows processed globally: 32447
Outlier count before clipping: 41

Skipping field time: unsupported OGR type: 10

Data retained: 91 rows after cleaning.
Trip max speed (12.07 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 90
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 87
Points removed: 3
Total rows processed globally: 32534
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (15.86 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 18
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 15
Points removed: 3
Total rows processed globally: 32549
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 581 rows after cleaning.
Trip max speed (58.20 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 580
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 570
Points removed: 10
Total rows processed globally: 33119
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 409 rows after cleaning.
Trip max speed (33.85 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 408
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 401
Points removed: 7
Total rows processed globally: 33520
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 29 rows after cleaning.
Trip max speed (4.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 28
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 1
Total rows processed globally: 33547
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 198 rows after cleaning.
Trip max speed (7.45 m/s) is within the cap of 11.11 m/s.
Initial rows: 197
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 196
Points removed: 1
Total rows processed globally: 33743
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 288 rows after cleaning.
Trip max speed (477.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 287
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 63
Extreme outliers (>2x cap): 85
Very extreme outliers (>5x cap): 22
Rows after removal: 201
Points removed: 86
Total rows processed globally: 33944
Outlier count before clipping: 77

Skipping field time: unsupported OGR type: 10

Data retained: 517 rows after cleaning.
Trip max speed (46.52 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 516
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 55
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 511
Points removed: 5
Total rows processed globally: 34455
Outlier count before clipping: 58

Skipping field time: unsupported OGR type: 10

Data retained: 989 rows after cleaning.
Trip max speed (51.04 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 988
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 0
Rows after removal: 975
Points removed: 13
Total rows processed globally: 35430
Outlier count before clipping: 37

Skipping field time: unsupported OGR type: 10

Data retained: 281 rows after cleaning.
Trip max speed (4.13 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 280
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 279
Points removed: 1
Total rows processed globally: 35709
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 350 rows after cleaning.
Trip max speed (65.60 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 349
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 340
Points removed: 9
Total rows processed globally: 36049
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (138.79 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 12
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 8
Points removed: 4
Total rows processed globally: 36057
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 602 rows after cleaning.
Trip max speed (58.43 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 601
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 597
Points removed: 4
Total rows processed globally: 36654
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 270 rows after cleaning.
Trip max speed (21.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 269
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 48
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 268
Points removed: 1
Total rows processed globally: 36922
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 284 rows after cleaning.
Trip max speed (17.26 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 283
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 275
Points removed: 8
Total rows processed globally: 37197
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 208 rows after cleaning.
Trip max speed (58.65 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 207
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 201
Points removed: 6
Total rows processed globally: 37398
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 63 rows after cleaning.
Trip max speed (401.24 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 62
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 58
Points removed: 4
Total rows processed globally: 37456
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 72 rows after cleaning.
Trip max speed (4.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 71
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 70
Points removed: 1
Total rows processed globally: 37526
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 1876 rows after cleaning.
Trip max speed (61.14 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 1875
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 937
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 0
Rows after removal: 1858
Points removed: 17
Total rows processed globally: 39384
Outlier count before clipping: 947

Skipping field time: unsupported OGR type: 10

Data retained: 546 rows after cleaning.
Trip max speed (9563.31 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 545
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 56
Extreme outliers (>2x cap): 45
Very extreme outliers (>5x cap): 10
Rows after removal: 499
Points removed: 46
Total rows processed globally: 39883
Outlier count before clipping: 63

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.13 m/s).
File Sub_Trajectories_Cleaned/20080725090000/taxi_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 384 rows after cleaning.
Trip max speed (3769.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 383
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 6
Rows after removal: 370
Points removed: 13
Total rows processed globally: 40253
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 14 rows after cleaning.
Trip max speed (84.34 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 13
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 11
Points removed: 2
Total rows processed globally: 40264
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 69 rows after cleaning.
Trip max speed (10.32 m/s) is within the cap of 11.11 m/s.
Initial rows: 68
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 67
Points removed: 1
Total rows processed globally: 40331
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (4.11 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 61
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 60
Points removed: 1
Total rows processed globally: 40391
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 492 rows after cleaning.
Trip max speed (115.09 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 491
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 3
Rows after removal: 476
Points removed: 15
Total rows processed globally: 40867
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10

Data retained: 87 rows after cleaning.
Trip max speed (14.05 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 86
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 81
Points removed: 5
Total rows processed globally: 40948
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 124 rows after cleaning.
Trip max speed (29.90 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 123
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 120
Points removed: 3
Total rows processed globally: 41068
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 108 rows after cleaning.
Trip max speed (15.19 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 107
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 102
Points removed: 5
Total rows processed globally: 41170
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 269 rows after cleaning.
Trip max speed (248.23 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 268
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 170
Very extreme outliers (>5x cap): 13
Rows after removal: 97
Points removed: 171
Total rows processed globally: 41267
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (3.62 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 27
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 26
Points removed: 1
Total rows processed globally: 41293
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1192 rows after cleaning.
Trip max speed (92.00 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1191
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 69
Extreme outliers (>2x cap): 25
Very extreme outliers (>5x cap): 1
Rows after removal: 1165
Points removed: 26
Total rows processed globally: 42458
Outlier count before clipping: 90

Skipping field time: unsupported OGR type: 10

Data retained: 208 rows after cleaning.
Trip max speed (44.29 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 207
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 33
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 4
Rows after removal: 196
Points removed: 11
Total rows processed globally: 42654
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.10 m/s).
File Sub_Trajectories_Cleaned/20090902012058/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 27 rows after cleaning.
Trip max speed (90.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 26
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 17
Points removed: 9
Total rows processed globally: 42671
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 586 rows after cleaning.
Trip max speed (20.47 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 585
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 584
Points removed: 1
Total rows processed globally: 43255
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 1404 rows after cleaning.
Trip max speed (44.08 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1403
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 319
Extreme outliers (>2x cap): 452
Very extreme outliers (>5x cap): 21
Rows after removal: 950
Points removed: 453
Total rows processed globally: 44205
Outlier count before clipping: 339

Skipping field time: unsupported OGR type: 10

Data retained: 105 rows after cleaning.
Trip max speed (37.42 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 104
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 102
Points removed: 2
Total rows processed globally: 44307
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 266 rows after cleaning.
Trip max speed (239.55 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 265
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 181
Very extreme outliers (>5x cap): 17
Rows after removal: 83
Points removed: 182
Total rows processed globally: 44390
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 231 rows after cleaning.
Trip max speed (2323.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 230
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 222
Points removed: 8
Total rows processed globally: 44612
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.92 m/s).
File Sub_Trajectories_Cleaned/20090826004628/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 47 rows after cleaning.
Trip max speed (10.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 46
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 44
Points removed: 2
Total rows processed globally: 44656
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 1149 rows after cleaning.
Trip max speed (36.29 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1148
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 102
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 0
Rows after removal: 1134
Points removed: 14
Total rows processed globally: 45790
Outlier count before clipping: 114

Skipping field time: unsupported OGR type: 10

Data retained: 342 rows after cleaning.
Trip max speed (4560.45 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 341
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 332
Points removed: 9
Total rows processed globally: 46122
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 940 rows after cleaning.
Trip max speed (93.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 939
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 927
Points removed: 12
Total rows processed globally: 47049
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 437 rows after cleaning.
Trip max speed (57.44 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 436
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 429
Points removed: 7
Total rows processed globally: 47478
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 1177 rows after cleaning.
Trip max speed (94.75 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1176
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 96
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 1166
Points removed: 10
Total rows processed globally: 48644
Outlier count before clipping: 101

Skipping field time: unsupported OGR type: 10

Data retained: 423 rows after cleaning.
Trip max speed (95.75 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 422
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 415
Points removed: 7
Total rows processed globally: 49059
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 176 rows after cleaning.
Trip max speed (346.04 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 175
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 169
Points removed: 6
Total rows processed globally: 49228
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 31 rows after cleaning.
Trip max speed (219.75 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 30
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 6
Rows after removal: 14
Points removed: 16
Total rows processed globally: 49242
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 134 rows after cleaning.
Trip max speed (28.36 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 133
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 131
Points removed: 2
Total rows processed globally: 49373
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 33 rows after cleaning.
Trip max speed (67.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 32
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 28
Points removed: 4
Total rows processed globally: 49401
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 56 rows after cleaning.
Trip max speed (25.88 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 55
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 53
Points removed: 2
Total rows processed globally: 49454
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 600 rows after cleaning.
Trip max speed (74.36 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 599
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 5
Rows after removal: 587
Points removed: 12
Total rows processed globally: 50041
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 25 rows after cleaning.
Trip max speed (10.13 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 24
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 22
Points removed: 2
Total rows processed globally: 50063
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 70 rows after cleaning.
Trip max speed (37.98 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 69
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 66
Points removed: 3
Total rows processed globally: 50129
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 33 rows after cleaning.
Trip max speed (2.55 m/s) is within the cap of 2.78 m/s.
Initial rows: 32
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 31
Points removed: 1
Total rows processed globally: 50160
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 219 rows after cleaning.
Trip max speed (419.95 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 218
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 129
Very extreme outliers (>5x cap): 9
Rows after removal: 88
Points removed: 130
Total rows processed globally: 50248
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 32 rows after cleaning.
Trip max speed (12.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 31
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 29
Points removed: 2
Total rows processed globally: 50277
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 176 rows after cleaning.
Trip max speed (15.88 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 175
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 173
Points removed: 2
Total rows processed globally: 50450
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (2.35 m/s) is within the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 21
Points removed: 1
Total rows processed globally: 50471
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 1073 rows after cleaning.
Trip max speed (43.02 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1072
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 88
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 0
Rows after removal: 1052
Points removed: 20
Total rows processed globally: 51523
Outlier count before clipping: 105

Skipping field time: unsupported OGR type: 10

Data retained: 720 rows after cleaning.
Trip max speed (4606.40 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 719
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 7
Rows after removal: 700
Points removed: 19
Total rows processed globally: 52223
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10

Data retained: 132 rows after cleaning.
Trip max speed (8.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 131
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 128
Points removed: 3
Total rows processed globally: 52351
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 751 rows after cleaning.
Trip max speed (74.65 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 750
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 28
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 6
Rows after removal: 728
Points removed: 22
Total rows processed globally: 53079
Outlier count before clipping: 61

Skipping field time: unsupported OGR type: 10

Data retained: 1017 rows after cleaning.
Trip max speed (691.17 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1016
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 94
Extreme outliers (>2x cap): 23
Very extreme outliers (>5x cap): 6
Rows after removal: 992
Points removed: 24
Total rows processed globally: 54071
Outlier count before clipping: 106

Skipping field time: unsupported OGR type: 10

Data retained: 271 rows after cleaning.
Trip max speed (7.52 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 270
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 268
Points removed: 2
Total rows processed globally: 54339
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 223 rows after cleaning.
Trip max speed (26.95 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 222
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 219
Points removed: 3
Total rows processed globally: 54558
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 73 rows after cleaning.
Trip max speed (61.73 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 72
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 2
Rows after removal: 54
Points removed: 18
Total rows processed globally: 54612
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 135 rows after cleaning.
Trip max speed (33.48 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 134
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 132
Points removed: 2
Total rows processed globally: 54744
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 100 rows after cleaning.
Trip max speed (2.66 m/s) is within the cap of 2.78 m/s.
Initial rows: 99
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 98
Points removed: 1
Total rows processed globally: 54842
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 507 rows after cleaning.
Trip max speed (29.41 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 506
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 497
Points removed: 9
Total rows processed globally: 55339
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 1196 rows after cleaning.
Trip max speed (198.12 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1195
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 196
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 5
Rows after removal: 1176
Points removed: 19
Total rows processed globally: 56515
Outlier count before clipping: 202

Skipping field time: unsupported OGR type: 10

Data retained: 1127 rows after cleaning.
Trip max speed (1787.80 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 1126
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 642
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 5
Rows after removal: 1109
Points removed: 17
Total rows processed globally: 57624
Outlier count before clipping: 649

Skipping field time: unsupported OGR type: 10

Data retained: 567 rows after cleaning.
Trip max speed (20.47 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 566
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 555
Points removed: 11
Total rows processed globally: 58179
Outlier count before clipping: 31

Skipping field time: unsupported OGR type: 10

Data retained: 311 rows after cleaning.
Trip max speed (24.13 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 310
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 301
Points removed: 9
Total rows processed globally: 58480
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 29 rows after cleaning.
Trip max speed (2.28 m/s) is within the cap of 2.78 m/s.
Initial rows: 28
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 1
Total rows processed globally: 58507
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 911 rows after cleaning.
Trip max speed (226.21 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 910
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 62
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 4
Rows after removal: 899
Points removed: 11
Total rows processed globally: 59406
Outlier count before clipping: 70

Skipping field time: unsupported OGR type: 10

Data retained: 49 rows after cleaning.
Trip max speed (3.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 48
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 47
Points removed: 1
Total rows processed globally: 59453
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 365 rows after cleaning.
Trip max speed (32.60 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 364
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 357
Points removed: 7
Total rows processed globally: 59810
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 51 rows after cleaning.
Trip max speed (4.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 50
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 49
Points removed: 1
Total rows processed globally: 59859
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 786 rows after cleaning.
Trip max speed (79.39 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 785
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 105
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 2
Rows after removal: 767
Points removed: 18
Total rows processed globally: 60626
Outlier count before clipping: 116

Skipping field time: unsupported OGR type: 10

Data retained: 253 rows after cleaning.
Trip max speed (20.56 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 252
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 244
Points removed: 8
Total rows processed globally: 60870
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 312 rows after cleaning.
Trip max speed (104.09 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 311
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 306
Points removed: 5
Total rows processed globally: 61176
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 167 rows after cleaning.
Trip max speed (1788.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 166
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 159
Points removed: 7
Total rows processed globally: 61335
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 159 rows after cleaning.
Trip max speed (23.87 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 158
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 156
Points removed: 2
Total rows processed globally: 61491
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10
/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/scipy/signal/_signaltools.py:1563: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '

Data retained: 10 rows after cleaning.
Trip max speed (27.40 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 9
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 5
Points removed: 4
Total rows processed globally: 61496
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 514 rows after cleaning.
Trip max speed (143.40 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 513
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 5
Rows after removal: 498
Points removed: 15
Total rows processed globally: 61994
Outlier count before clipping: 36

Skipping field time: unsupported OGR type: 10

Data retained: 271 rows after cleaning.
Trip max speed (19.56 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 270
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 265
Points removed: 5
Total rows processed globally: 62259
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 50 rows after cleaning.
Trip max speed (2.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 49
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 48
Points removed: 1
Total rows processed globally: 62307
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 678 rows after cleaning.
Trip max speed (58.19 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 677
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 62
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 668
Points removed: 9
Total rows processed globally: 62975
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10

Data retained: 86 rows after cleaning.
Trip max speed (6.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 85
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 83
Points removed: 2
Total rows processed globally: 63058
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 955 rows after cleaning.
Trip max speed (270.23 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 954
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 668
Extreme outliers (>2x cap): 28
Very extreme outliers (>5x cap): 2
Rows after removal: 925
Points removed: 29
Total rows processed globally: 63983
Outlier count before clipping: 668

Skipping field time: unsupported OGR type: 10

Data retained: 387 rows after cleaning.
Trip max speed (23.24 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 386
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 5
Rows after removal: 371
Points removed: 15
Total rows processed globally: 64354
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 220 rows after cleaning.
Trip max speed (14.07 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 219
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 217
Points removed: 2
Total rows processed globally: 64571
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 1062 rows after cleaning.
Trip max speed (113.01 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1061
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 7
Rows after removal: 1041
Points removed: 20
Total rows processed globally: 65612
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 623 rows after cleaning.
Trip max speed (47.22 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 622
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 3
Rows after removal: 604
Points removed: 18
Total rows processed globally: 66216
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 627 rows after cleaning.
Trip max speed (44.94 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 626
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 617
Points removed: 9
Total rows processed globally: 66833
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 94 rows after cleaning.
Trip max speed (7.19 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 93
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 91
Points removed: 2
Total rows processed globally: 66924
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (282.57 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 20
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 16
Points removed: 4
Total rows processed globally: 66940
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.03 m/s).
File Sub_Trajectories_Cleaned/20090819113327/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 32 rows after cleaning.
Trip max speed (3.52 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 31
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 30
Points removed: 1
Total rows processed globally: 66970
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 417 rows after cleaning.
Trip max speed (180.87 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 416
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 31
Extreme outliers (>2x cap): 267
Very extreme outliers (>5x cap): 12
Rows after removal: 148
Points removed: 268
Total rows processed globally: 67118
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 74 rows after cleaning.
Trip max speed (12.17 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 73
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 69
Points removed: 4
Total rows processed globally: 67187
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 91 rows after cleaning.
Trip max speed (394.30 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 90
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 37
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 5
Rows after removal: 83
Points removed: 7
Total rows processed globally: 67270
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10

Data retained: 454 rows after cleaning.
Trip max speed (280.52 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 453
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 7
Rows after removal: 437
Points removed: 16
Total rows processed globally: 67707
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 2007 rows after cleaning.
Trip max speed (275.93 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 2006
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 141
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 2
Rows after removal: 1987
Points removed: 19
Total rows processed globally: 69694
Outlier count before clipping: 154

Skipping field time: unsupported OGR type: 10

Data retained: 913 rows after cleaning.
Trip max speed (7472.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 912
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 30
Very extreme outliers (>5x cap): 12
Rows after removal: 881
Points removed: 31
Total rows processed globally: 70575
Outlier count before clipping: 59

Skipping field time: unsupported OGR type: 10

Data retained: 164 rows after cleaning.
Trip max speed (30.43 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 163
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 155
Points removed: 8
Total rows processed globally: 70730
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20080819144129/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 268 rows after cleaning.
Trip max speed (110.02 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 267
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 72
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 257
Points removed: 10
Total rows processed globally: 70987
Outlier count before clipping: 79

Skipping field time: unsupported OGR type: 10

Data retained: 65 rows after cleaning.
Trip max speed (6.60 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 64
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 62
Points removed: 2
Total rows processed globally: 71049
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 181 rows after cleaning.
Trip max speed (108.85 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 180
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 174
Points removed: 6
Total rows processed globally: 71223
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.95 m/s).
File Sub_Trajectories_Cleaned/20090911004404/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 47 rows after cleaning.
Trip max speed (9.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 46
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 44
Points removed: 2
Total rows processed globally: 71267
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 63 rows after cleaning.
Trip max speed (19.38 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 62
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 60
Points removed: 2
Total rows processed globally: 71327
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 25 rows after cleaning.
Trip max speed (5.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 24
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 22
Points removed: 2
Total rows processed globally: 71349
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1410 rows after cleaning.
Trip max speed (273.45 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1409
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 195
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 3
Rows after removal: 1384
Points removed: 25
Total rows processed globally: 72733
Outlier count before clipping: 212

Skipping field time: unsupported OGR type: 10

Data retained: 375 rows after cleaning.
Trip max speed (183.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 374
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 365
Points removed: 9
Total rows processed globally: 73098
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 266 rows after cleaning.
Trip max speed (316.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 265
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 258
Points removed: 7
Total rows processed globally: 73356
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 925 rows after cleaning.
Trip max speed (24.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 924
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 36
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 5
Rows after removal: 908
Points removed: 16
Total rows processed globally: 74264
Outlier count before clipping: 50

Skipping field time: unsupported OGR type: 10

Data retained: 54 rows after cleaning.
Trip max speed (22.39 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 53
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 51
Points removed: 2
Total rows processed globally: 74315
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 74 rows after cleaning.
Trip max speed (10.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 73
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 71
Points removed: 2
Total rows processed globally: 74386
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 349 rows after cleaning.
Trip max speed (64.03 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 348
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 47
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 1
Rows after removal: 337
Points removed: 11
Total rows processed globally: 74723
Outlier count before clipping: 52

Skipping field time: unsupported OGR type: 10

Data retained: 42 rows after cleaning.
Trip max speed (82.70 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 41
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 38
Points removed: 3
Total rows processed globally: 74761
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 739 rows after cleaning.
Trip max speed (64.25 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 738
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 274
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 728
Points removed: 10
Total rows processed globally: 75489
Outlier count before clipping: 276

Skipping field time: unsupported OGR type: 10

Data retained: 53 rows after cleaning.
Trip max speed (39.45 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 52
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 47
Points removed: 5
Total rows processed globally: 75536
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 1387 rows after cleaning.
Trip max speed (57.74 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1386
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 121
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 1
Rows after removal: 1365
Points removed: 21
Total rows processed globally: 76901
Outlier count before clipping: 136

Skipping field time: unsupported OGR type: 10

Data retained: 15 rows after cleaning.
Trip max speed (45.64 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 14
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 7
Points removed: 7
Total rows processed globally: 76908
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.74 m/s).
File Sub_Trajectories_Cleaned/20090827005251/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 43 rows after cleaning.
Trip max speed (14.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 42
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 40
Points removed: 2
Total rows processed globally: 76948
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 202 rows after cleaning.
Trip max speed (23.81 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 201
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 197
Points removed: 4
Total rows processed globally: 77145
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (4.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 15
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 14
Points removed: 1
Total rows processed globally: 77159
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 399 rows after cleaning.
Trip max speed (57.74 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 398
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 391
Points removed: 7
Total rows processed globally: 77550
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 84 rows after cleaning.
Trip max speed (777.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 83
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 81
Points removed: 2
Total rows processed globally: 77631
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 152 rows after cleaning.
Trip max speed (18.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 151
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 145
Points removed: 6
Total rows processed globally: 77776
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 264 rows after cleaning.
Trip max speed (52.79 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 263
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 137
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 0
Rows after removal: 253
Points removed: 10
Total rows processed globally: 78029
Outlier count before clipping: 144

Skipping field time: unsupported OGR type: 10

Data retained: 31 rows after cleaning.
Trip max speed (2.28 m/s) is within the cap of 2.78 m/s.
Initial rows: 30
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 29
Points removed: 1
Total rows processed globally: 78058
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 843 rows after cleaning.
Trip max speed (36.18 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 842
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 1
Rows after removal: 825
Points removed: 17
Total rows processed globally: 78883
Outlier count before clipping: 46

Skipping field time: unsupported OGR type: 10

Data retained: 1120 rows after cleaning.
Trip max speed (75.56 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1119
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 145
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 1110
Points removed: 9
Total rows processed globally: 79993
Outlier count before clipping: 152

Skipping field time: unsupported OGR type: 10

Data retained: 504 rows after cleaning.
Trip max speed (7059.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 503
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 4
Rows after removal: 492
Points removed: 11
Total rows processed globally: 80485
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 104 rows after cleaning.
Trip max speed (29.32 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 103
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 101
Points removed: 2
Total rows processed globally: 80586
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20111022092135/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 475 rows after cleaning.
Trip max speed (9.52 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 474
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 473
Points removed: 1
Total rows processed globally: 81059
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 153 rows after cleaning.
Trip max speed (4.05 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 152
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 151
Points removed: 1
Total rows processed globally: 81210
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 30 rows after cleaning.
Trip max speed (2.42 m/s) is within the cap of 11.11 m/s.
Initial rows: 29
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 28
Points removed: 1
Total rows processed globally: 81238
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (2.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 45
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 44
Points removed: 1
Total rows processed globally: 81282
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 389 rows after cleaning.
Trip max speed (68.41 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 388
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 377
Points removed: 11
Total rows processed globally: 81659
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 44 rows after cleaning.
Trip max speed (5.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 43
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 41
Points removed: 2
Total rows processed globally: 81700
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (18.29 m/s).
File Sub_Trajectories_Cleaned/20081102022639/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 436 rows after cleaning.
Trip max speed (21.94 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 435
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 101
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 434
Points removed: 1
Total rows processed globally: 82134
Outlier count before clipping: 101

Skipping field time: unsupported OGR type: 10

Data retained: 81 rows after cleaning.
Trip max speed (52.11 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 80
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 78
Points removed: 2
Total rows processed globally: 82212
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 168 rows after cleaning.
Trip max speed (8.15 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 167
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 165
Points removed: 2
Total rows processed globally: 82377
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 448 rows after cleaning.
Trip max speed (93.00 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 447
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 3
Rows after removal: 434
Points removed: 13
Total rows processed globally: 82811
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 15 rows after cleaning.
Trip max speed (13.53 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 14
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 3
Total rows processed globally: 82822
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 327 rows after cleaning.
Trip max speed (183.11 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 326
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 53
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 322
Points removed: 4
Total rows processed globally: 83144
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 67 rows after cleaning.
Trip max speed (1581.37 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 66
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 63
Points removed: 3
Total rows processed globally: 83207
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 188 rows after cleaning.
Trip max speed (27.82 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 187
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 185
Points removed: 2
Total rows processed globally: 83392
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 518 rows after cleaning.
Trip max speed (64.29 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 517
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 513
Points removed: 4
Total rows processed globally: 83905
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 119 rows after cleaning.
Trip max speed (9.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 118
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 114
Points removed: 4
Total rows processed globally: 84019
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 392 rows after cleaning.
Trip max speed (87.22 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 391
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 35
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 2
Rows after removal: 376
Points removed: 15
Total rows processed globally: 84395
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 95 rows after cleaning.
Trip max speed (8.00 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 94
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 89
Points removed: 5
Total rows processed globally: 84484
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 121 rows after cleaning.
Trip max speed (9.96 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 120
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 119
Points removed: 1
Total rows processed globally: 84603
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 93 rows after cleaning.
Trip max speed (30.11 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 92
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 87
Points removed: 5
Total rows processed globally: 84690
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 87 rows after cleaning.
Trip max speed (6.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 86
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 84
Points removed: 2
Total rows processed globally: 84774
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 432 rows after cleaning.
Trip max speed (44.91 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 431
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 423
Points removed: 8
Total rows processed globally: 85197
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 1205 rows after cleaning.
Trip max speed (544.28 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1204
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 107
Extreme outliers (>2x cap): 781
Very extreme outliers (>5x cap): 36
Rows after removal: 422
Points removed: 782
Total rows processed globally: 85619
Outlier count before clipping: 137

Skipping field time: unsupported OGR type: 10

Data retained: 416 rows after cleaning.
Trip max speed (66.35 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 415
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 60
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 405
Points removed: 10
Total rows processed globally: 86024
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.93 m/s).
File Sub_Trajectories_Cleaned/20090922005527/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 72 rows after cleaning.
Trip max speed (2077.21 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 71
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 68
Points removed: 3
Total rows processed globally: 86092
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 449 rows after cleaning.
Trip max speed (34.18 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 448
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 446
Points removed: 2
Total rows processed globally: 86538
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 378 rows after cleaning.
Trip max speed (10.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 377
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 371
Points removed: 6
Total rows processed globally: 86909
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 222 rows after cleaning.
Trip max speed (37.11 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 221
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 51
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 217
Points removed: 4
Total rows processed globally: 87126
Outlier count before clipping: 54

Skipping field time: unsupported OGR type: 10

Data retained: 32 rows after cleaning.
Trip max speed (2.09 m/s) is within the cap of 2.78 m/s.
Initial rows: 31
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 30
Points removed: 1
Total rows processed globally: 87156
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 29 rows after cleaning.
Trip max speed (5.11 m/s) is within the cap of 11.11 m/s.
Initial rows: 28
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 1
Total rows processed globally: 87183
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (8.56 m/s) is within the cap of 13.89 m/s.
Initial rows: 12
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 87194
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (5 rows).
File Sub_Trajectories_Cleaned/20071010063513/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 533 rows after cleaning.
Trip max speed (145.44 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 532
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 43
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 525
Points removed: 7
Total rows processed globally: 87719
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 177 rows after cleaning.
Trip max speed (13.00 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 176
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 174
Points removed: 2
Total rows processed globally: 87893
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 152 rows after cleaning.
Trip max speed (36.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 151
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 148
Points removed: 3
Total rows processed globally: 88041
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.58 m/s).
File Sub_Trajectories_Cleaned/20090924003152/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 120 rows after cleaning.
Trip max speed (3473.75 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 119
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 4
Rows after removal: 111
Points removed: 8
Total rows processed globally: 88152
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 753 rows after cleaning.
Trip max speed (72.60 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 752
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 2
Rows after removal: 737
Points removed: 15
Total rows processed globally: 88889
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 575 rows after cleaning.
Trip max speed (40.87 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 574
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 5
Rows after removal: 555
Points removed: 19
Total rows processed globally: 89444
Outlier count before clipping: 42

Skipping field time: unsupported OGR type: 10
/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/scipy/signal/_signaltools.py:1563: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '

Data retained: 11 rows after cleaning.
Trip max speed (100.09 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 10
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 4
Points removed: 6
Total rows processed globally: 89448
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 11 rows after cleaning.
Trip max speed (3.59 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 10
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 1
Total rows processed globally: 89457
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 430 rows after cleaning.
Trip max speed (41.60 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 429
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 172
Extreme outliers (>2x cap): 55
Very extreme outliers (>5x cap): 2
Rows after removal: 373
Points removed: 56
Total rows processed globally: 89830
Outlier count before clipping: 173

Skipping field time: unsupported OGR type: 10

Data retained: 230 rows after cleaning.
Trip max speed (61.11 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 229
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 226
Points removed: 3
Total rows processed globally: 90056
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (28.33 m/s).
File Sub_Trajectories_Cleaned/20081102030158/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 53 rows after cleaning.
Trip max speed (7.22 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 52
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 50
Points removed: 2
Total rows processed globally: 90106
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 326 rows after cleaning.
Trip max speed (58.28 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 325
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 1
Rows after removal: 315
Points removed: 10
Total rows processed globally: 90421
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (12.91 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 33
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 29
Points removed: 4
Total rows processed globally: 90450
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 1012 rows after cleaning.
Trip max speed (224.33 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1011
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 998
Points removed: 13
Total rows processed globally: 91448
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 1117 rows after cleaning.
Trip max speed (436.04 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1116
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 160
Extreme outliers (>2x cap): 30
Very extreme outliers (>5x cap): 10
Rows after removal: 1085
Points removed: 31
Total rows processed globally: 92533
Outlier count before clipping: 176

Skipping field time: unsupported OGR type: 10

Data retained: 765 rows after cleaning.
Trip max speed (64.26 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 764
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 318
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 753
Points removed: 11
Total rows processed globally: 93286
Outlier count before clipping: 321

Skipping field time: unsupported OGR type: 10

Data retained: 380 rows after cleaning.
Trip max speed (40.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 379
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 4
Rows after removal: 370
Points removed: 9
Total rows processed globally: 93656
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 226 rows after cleaning.
Trip max speed (264.51 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 225
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 158
Very extreme outliers (>5x cap): 11
Rows after removal: 66
Points removed: 159
Total rows processed globally: 93722
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 30 rows after cleaning.
Trip max speed (2.39 m/s) is within the cap of 2.78 m/s.
Initial rows: 29
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 28
Points removed: 1
Total rows processed globally: 93750
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 92 rows after cleaning.
Trip max speed (15.55 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 91
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 89
Points removed: 2
Total rows processed globally: 93839
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.57 m/s).
File Sub_Trajectories_Cleaned/20090913233334/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 115 rows after cleaning.
Trip max speed (2084.81 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 114
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 106
Points removed: 8
Total rows processed globally: 93945
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 125 rows after cleaning.
Trip max speed (85.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 124
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 6
Rows after removal: 114
Points removed: 10
Total rows processed globally: 94059
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 865 rows after cleaning.
Trip max speed (352.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 864
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 854
Points removed: 10
Total rows processed globally: 94913
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 492 rows after cleaning.
Trip max speed (15.34 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 491
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 1
Rows after removal: 481
Points removed: 10
Total rows processed globally: 95394
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 778 rows after cleaning.
Trip max speed (44.22 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 777
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 43
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 0
Rows after removal: 764
Points removed: 13
Total rows processed globally: 96158
Outlier count before clipping: 47

Skipping field time: unsupported OGR type: 10

Data retained: 366 rows after cleaning.
Trip max speed (77.95 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 365
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 232
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 359
Points removed: 6
Total rows processed globally: 96517
Outlier count before clipping: 234

Skipping field time: unsupported OGR type: 10

Data retained: 155 rows after cleaning.
Trip max speed (3754.32 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 154
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 146
Points removed: 8
Total rows processed globally: 96663
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 405 rows after cleaning.
Trip max speed (36.25 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 404
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 397
Points removed: 7
Total rows processed globally: 97060
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 82 rows after cleaning.
Trip max speed (1672.72 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 81
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 75
Points removed: 6
Total rows processed globally: 97135
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (252.11 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 18
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 15
Points removed: 3
Total rows processed globally: 97150
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 1191 rows after cleaning.
Trip max speed (82.74 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1190
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 2
Rows after removal: 1168
Points removed: 22
Total rows processed globally: 98318
Outlier count before clipping: 34

Skipping field time: unsupported OGR type: 10

Data retained: 126 rows after cleaning.
Trip max speed (84.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 125
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 119
Points removed: 6
Total rows processed globally: 98437
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 45 rows after cleaning.
Trip max speed (19.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 44
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 42
Points removed: 2
Total rows processed globally: 98479
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 223 rows after cleaning.
Trip max speed (23.42 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 222
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 220
Points removed: 2
Total rows processed globally: 98699
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 1015 rows after cleaning.
Trip max speed (53.53 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1014
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 1002
Points removed: 12
Total rows processed globally: 99701
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 26 rows after cleaning.
Trip max speed (4.98 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 25
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 24
Points removed: 1
Total rows processed globally: 99725
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 100 rows after cleaning.
Trip max speed (230.93 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 99
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 91
Points removed: 8
Total rows processed globally: 99816
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (10.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 33
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 31
Points removed: 2
Total rows processed globally: 99847
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 418 rows after cleaning.
Trip max speed (56.79 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 417
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 194
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 1
Rows after removal: 406
Points removed: 11
Total rows processed globally: 100253
Outlier count before clipping: 203

Skipping field time: unsupported OGR type: 10

Data retained: 210 rows after cleaning.
Trip max speed (3118.25 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 209
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 4
Rows after removal: 203
Points removed: 6
Total rows processed globally: 100456
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 301 rows after cleaning.
Trip max speed (42.95 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 300
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 297
Points removed: 3
Total rows processed globally: 100753
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 363 rows after cleaning.
Trip max speed (78.73 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 362
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 3
Rows after removal: 354
Points removed: 8
Total rows processed globally: 101107
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 86 rows after cleaning.
Trip max speed (263.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 85
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 80
Points removed: 5
Total rows processed globally: 101187
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 683 rows after cleaning.
Trip max speed (39.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 682
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 51
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 678
Points removed: 4
Total rows processed globally: 101865
Outlier count before clipping: 54

Skipping field time: unsupported OGR type: 10

Data retained: 107 rows after cleaning.
Trip max speed (45.72 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 106
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 99
Points removed: 7
Total rows processed globally: 101964
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 182 rows after cleaning.
Trip max speed (25.84 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 181
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 179
Points removed: 2
Total rows processed globally: 102143
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 108 rows after cleaning.
Trip max speed (1.74 m/s) is within the cap of 2.78 m/s.
Initial rows: 107
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 106
Points removed: 1
Total rows processed globally: 102249
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 976 rows after cleaning.
Trip max speed (51.11 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 975
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 1
Rows after removal: 961
Points removed: 14
Total rows processed globally: 103210
Outlier count before clipping: 45

Skipping field time: unsupported OGR type: 10

Data retained: 1083 rows after cleaning.
Trip max speed (84.94 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1082
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 184
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 1
Rows after removal: 1060
Points removed: 22
Total rows processed globally: 104270
Outlier count before clipping: 198

Skipping field time: unsupported OGR type: 10

Data retained: 636 rows after cleaning.
Trip max speed (95.14 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 635
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 160
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 624
Points removed: 11
Total rows processed globally: 104894
Outlier count before clipping: 164

Skipping field time: unsupported OGR type: 10

Data retained: 399 rows after cleaning.
Trip max speed (29.85 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 398
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 387
Points removed: 11
Total rows processed globally: 105281
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 324 rows after cleaning.
Trip max speed (23.33 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 323
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 320
Points removed: 3
Total rows processed globally: 105601
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 364 rows after cleaning.
Trip max speed (54.13 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 363
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 9
Rows after removal: 346
Points removed: 17
Total rows processed globally: 105947
Outlier count before clipping: 31

Skipping field time: unsupported OGR type: 10

Data retained: 269 rows after cleaning.
Trip max speed (176.94 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 268
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 258
Points removed: 10
Total rows processed globally: 106205
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 373 rows after cleaning.
Trip max speed (1839.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 372
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 4
Rows after removal: 362
Points removed: 10
Total rows processed globally: 106567
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 129 rows after cleaning.
Trip max speed (8.63 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 128
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 126
Points removed: 2
Total rows processed globally: 106693
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (20.48 m/s).
File Sub_Trajectories_Cleaned/20090815062008/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 187 rows after cleaning.
Trip max speed (2219.29 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 186
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 181
Points removed: 5
Total rows processed globally: 106874
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 392 rows after cleaning.
Trip max speed (30.97 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 391
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 383
Points removed: 8
Total rows processed globally: 107257
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 428 rows after cleaning.
Trip max speed (266.54 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 427
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 4
Rows after removal: 418
Points removed: 9
Total rows processed globally: 107675
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 4644 rows after cleaning.
Trip max speed (245.12 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 4643
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 2241
Extreme outliers (>2x cap): 27
Very extreme outliers (>5x cap): 4
Rows after removal: 4615
Points removed: 28
Total rows processed globally: 112290
Outlier count before clipping: 2253

Skipping field time: unsupported OGR type: 10

Data retained: 235 rows after cleaning.
Trip max speed (62.44 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 234
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 228
Points removed: 6
Total rows processed globally: 112518
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 338 rows after cleaning.
Trip max speed (25.10 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 337
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 326
Points removed: 11
Total rows processed globally: 112844
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 55 rows after cleaning.
Trip max speed (182.24 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 54
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 52
Points removed: 2
Total rows processed globally: 112896
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 305 rows after cleaning.
Trip max speed (48.02 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 304
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 121
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 296
Points removed: 8
Total rows processed globally: 113192
Outlier count before clipping: 126

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (43.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 15
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 11
Points removed: 4
Total rows processed globally: 113203
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 1087 rows after cleaning.
Trip max speed (43.05 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1086
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 165
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 0
Rows after removal: 1071
Points removed: 15
Total rows processed globally: 114274
Outlier count before clipping: 175

Skipping field time: unsupported OGR type: 10

Data retained: 237 rows after cleaning.
Trip max speed (20.51 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 236
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 227
Points removed: 9
Total rows processed globally: 114501
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 1598 rows after cleaning.
Trip max speed (29.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1597
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 32
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 0
Rows after removal: 1577
Points removed: 20
Total rows processed globally: 116078
Outlier count before clipping: 58

Skipping field time: unsupported OGR type: 10

Data retained: 31 rows after cleaning.
Trip max speed (21.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 30
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 28
Points removed: 2
Total rows processed globally: 116106
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (9 rows).
File Sub_Trajectories_Cleaned/20080315052314/bike_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 11 rows after cleaning.
Trip max speed (4.15 m/s) is within the cap of 11.11 m/s.
Initial rows: 10
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 1
Total rows processed globally: 116115
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20080315052314/walk_cleaned.geojson did not pass cleaning. Skipping.
Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20080912085259/bike_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 51 rows after cleaning.
Trip max speed (2.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 50
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 49
Points removed: 1
Total rows processed globally: 116164
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (44.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 27
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 1
Rows after removal: 16
Points removed: 11
Total rows processed globally: 116180
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 316 rows after cleaning.
Trip max speed (26.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 315
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 6
Rows after removal: 304
Points removed: 11
Total rows processed globally: 116484
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 628 rows after cleaning.
Trip max speed (115.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 627
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 58
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 1
Rows after removal: 614
Points removed: 13
Total rows processed globally: 117098
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (18.82 m/s).
File Sub_Trajectories_Cleaned/20081105235106/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 293 rows after cleaning.
Trip max speed (18.28 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 292
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 281
Points removed: 11
Total rows processed globally: 117379
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (10.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 20
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 19
Points removed: 1
Total rows processed globally: 117398
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 440 rows after cleaning.
Trip max speed (188.51 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 439
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 5
Rows after removal: 428
Points removed: 11
Total rows processed globally: 117826
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (2.70 m/s) is within the cap of 2.78 m/s.
Initial rows: 11
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 10
Points removed: 1
Total rows processed globally: 117836
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 280 rows after cleaning.
Trip max speed (206.25 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 279
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 31
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 272
Points removed: 7
Total rows processed globally: 118108
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 104 rows after cleaning.
Trip max speed (1733.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 103
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 97
Points removed: 6
Total rows processed globally: 118205
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 206 rows after cleaning.
Trip max speed (24.34 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 205
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 195
Points removed: 10
Total rows processed globally: 118400
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (15.34 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 93
Points removed: 5
Total rows processed globally: 118493
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 414 rows after cleaning.
Trip max speed (65.03 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 413
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 406
Points removed: 7
Total rows processed globally: 118899
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 825 rows after cleaning.
Trip max speed (39.98 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 824
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 815
Points removed: 9
Total rows processed globally: 119714
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 64 rows after cleaning.
Trip max speed (54.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 63
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 58
Points removed: 5
Total rows processed globally: 119772
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 718 rows after cleaning.
Trip max speed (99.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 717
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 35
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 6
Rows after removal: 703
Points removed: 14
Total rows processed globally: 120475
Outlier count before clipping: 45

Skipping field time: unsupported OGR type: 10

Data retained: 335 rows after cleaning.
Trip max speed (45.01 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 334
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 322
Points removed: 12
Total rows processed globally: 120797
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 541 rows after cleaning.
Trip max speed (61.53 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 540
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 534
Points removed: 6
Total rows processed globally: 121331
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 291 rows after cleaning.
Trip max speed (514.49 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 290
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 6
Rows after removal: 278
Points removed: 12
Total rows processed globally: 121609
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 88 rows after cleaning.
Trip max speed (3.40 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 87
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 86
Points removed: 1
Total rows processed globally: 121695
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 55 rows after cleaning.
Trip max speed (709.09 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 54
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 51
Points removed: 3
Total rows processed globally: 121746
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (19.39 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 45
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 43
Points removed: 2
Total rows processed globally: 121789
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 298 rows after cleaning.
Trip max speed (230.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 297
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 183
Very extreme outliers (>5x cap): 13
Rows after removal: 113
Points removed: 184
Total rows processed globally: 121902
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (9 rows).
File Sub_Trajectories_Cleaned/20090624084534/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 18 rows after cleaning.
Trip max speed (1.69 m/s) is within the cap of 2.78 m/s.
Initial rows: 17
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 1
Total rows processed globally: 121918
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 433 rows after cleaning.
Trip max speed (74.22 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 432
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 423
Points removed: 9
Total rows processed globally: 122341
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 578 rows after cleaning.
Trip max speed (55.13 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 577
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 146
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 573
Points removed: 4
Total rows processed globally: 122914
Outlier count before clipping: 148

Skipping field time: unsupported OGR type: 10

Data retained: 333 rows after cleaning.
Trip max speed (20.32 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 332
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 322
Points removed: 10
Total rows processed globally: 123236
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (92.76 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 20
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 16
Points removed: 4
Total rows processed globally: 123252
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 26 rows after cleaning.
Trip max speed (15.63 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 25
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 23
Points removed: 2
Total rows processed globally: 123275
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 543 rows after cleaning.
Trip max speed (79.98 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 542
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 537
Points removed: 5
Total rows processed globally: 123812
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 298 rows after cleaning.
Trip max speed (5.31 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 297
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 296
Points removed: 1
Total rows processed globally: 124108
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 522 rows after cleaning.
Trip max speed (107.48 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 521
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 28
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 3
Rows after removal: 501
Points removed: 20
Total rows processed globally: 124609
Outlier count before clipping: 46

Skipping field time: unsupported OGR type: 10

Data retained: 17 rows after cleaning.
Trip max speed (2.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 16
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 15
Points removed: 1
Total rows processed globally: 124624
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 270 rows after cleaning.
Trip max speed (18.06 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 269
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 55
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 268
Points removed: 1
Total rows processed globally: 124892
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 185 rows after cleaning.
Trip max speed (145.99 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 184
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 5
Rows after removal: 172
Points removed: 12
Total rows processed globally: 125064
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 237 rows after cleaning.
Trip max speed (1418.32 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 236
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 230
Points removed: 6
Total rows processed globally: 125294
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.85 m/s).
File Sub_Trajectories_Cleaned/20090908120539/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 85 rows after cleaning.
Trip max speed (11.55 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 84
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 81
Points removed: 3
Total rows processed globally: 125375
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 61 rows after cleaning.
Trip max speed (3.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 60
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 59
Points removed: 1
Total rows processed globally: 125434
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 459 rows after cleaning.
Trip max speed (28.23 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 458
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 40
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 452
Points removed: 6
Total rows processed globally: 125886
Outlier count before clipping: 45

Skipping field time: unsupported OGR type: 10

Data retained: 40 rows after cleaning.
Trip max speed (27.95 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 39
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 36
Points removed: 3
Total rows processed globally: 125922
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 246 rows after cleaning.
Trip max speed (37.17 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 245
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 118
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 242
Points removed: 3
Total rows processed globally: 126164
Outlier count before clipping: 120

Skipping field time: unsupported OGR type: 10

Data retained: 303 rows after cleaning.
Trip max speed (10.09 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 302
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 295
Points removed: 7
Total rows processed globally: 126459
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 45 rows after cleaning.
Trip max speed (63.05 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 44
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 9
Rows after removal: 24
Points removed: 20
Total rows processed globally: 126483
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 146 rows after cleaning.
Trip max speed (17.61 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 145
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 144
Points removed: 1
Total rows processed globally: 126627
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 341 rows after cleaning.
Trip max speed (49.27 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 340
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 5
Rows after removal: 330
Points removed: 10
Total rows processed globally: 126957
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 155 rows after cleaning.
Trip max speed (20.52 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 154
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 79
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 152
Points removed: 2
Total rows processed globally: 127109
Outlier count before clipping: 79

Skipping field time: unsupported OGR type: 10

Data retained: 309 rows after cleaning.
Trip max speed (63.54 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 308
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 157
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 0
Rows after removal: 295
Points removed: 13
Total rows processed globally: 127404
Outlier count before clipping: 164

Skipping field time: unsupported OGR type: 10

Data retained: 215 rows after cleaning.
Trip max speed (15.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 214
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 209
Points removed: 5
Total rows processed globally: 127613
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 1310 rows after cleaning.
Trip max speed (50.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1309
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 4
Rows after removal: 1289
Points removed: 20
Total rows processed globally: 128902
Outlier count before clipping: 58

Skipping field time: unsupported OGR type: 10

Data retained: 1301 rows after cleaning.
Trip max speed (130.05 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1300
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 91
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 5
Rows after removal: 1279
Points removed: 21
Total rows processed globally: 130181
Outlier count before clipping: 106

Skipping field time: unsupported OGR type: 10

Data retained: 912 rows after cleaning.
Trip max speed (5891.36 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 911
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 106
Extreme outliers (>2x cap): 27
Very extreme outliers (>5x cap): 12
Rows after removal: 883
Points removed: 28
Total rows processed globally: 131064
Outlier count before clipping: 127

Skipping field time: unsupported OGR type: 10

Data retained: 304 rows after cleaning.
Trip max speed (56.51 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 303
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 299
Points removed: 4
Total rows processed globally: 131363
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 70 rows after cleaning.
Trip max speed (9.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 69
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 67
Points removed: 2
Total rows processed globally: 131430
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 358 rows after cleaning.
Trip max speed (68.07 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 357
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 345
Points removed: 12
Total rows processed globally: 131775
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 86 rows after cleaning.
Trip max speed (17.26 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 85
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 80
Points removed: 5
Total rows processed globally: 131855
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20111224111715/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 513 rows after cleaning.
Trip max speed (231.69 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 512
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 67
Extreme outliers (>2x cap): 34
Very extreme outliers (>5x cap): 5
Rows after removal: 477
Points removed: 35
Total rows processed globally: 132332
Outlier count before clipping: 88

Skipping field time: unsupported OGR type: 10
/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/scipy/signal/_signaltools.py:1563: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '

Data retained: 17 rows after cleaning.
Trip max speed (21.39 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 16
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 5
Points removed: 11
Total rows processed globally: 132337
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 214 rows after cleaning.
Trip max speed (37.15 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 213
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 210
Points removed: 3
Total rows processed globally: 132547
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 72 rows after cleaning.
Trip max speed (103.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 71
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 3
Rows after removal: 51
Points removed: 20
Total rows processed globally: 132598
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 94 rows after cleaning.
Trip max speed (14.65 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 93
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 92
Points removed: 1
Total rows processed globally: 132690
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 972 rows after cleaning.
Trip max speed (96.30 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 971
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 159
Extreme outliers (>2x cap): 25
Very extreme outliers (>5x cap): 1
Rows after removal: 945
Points removed: 26
Total rows processed globally: 133635
Outlier count before clipping: 176

Skipping field time: unsupported OGR type: 10

Data retained: 223 rows after cleaning.
Trip max speed (21.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 222
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 220
Points removed: 2
Total rows processed globally: 133855
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (4.97 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 17
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 1
Total rows processed globally: 133871
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 221 rows after cleaning.
Trip max speed (422.58 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 220
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 159
Very extreme outliers (>5x cap): 15
Rows after removal: 60
Points removed: 160
Total rows processed globally: 133931
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 185 rows after cleaning.
Trip max speed (2319.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 184
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 180
Points removed: 4
Total rows processed globally: 134111
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 427 rows after cleaning.
Trip max speed (61.65 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 426
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 421
Points removed: 5
Total rows processed globally: 134532
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 147 rows after cleaning.
Trip max speed (37.22 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 146
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 140
Points removed: 6
Total rows processed globally: 134672
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 64 rows after cleaning.
Trip max speed (31.05 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 63
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 59
Points removed: 4
Total rows processed globally: 134731
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 70 rows after cleaning.
Trip max speed (4.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 69
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 68
Points removed: 1
Total rows processed globally: 134799
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 354 rows after cleaning.
Trip max speed (56.95 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 353
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 4
Rows after removal: 344
Points removed: 9
Total rows processed globally: 135143
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 792 rows after cleaning.
Trip max speed (48.13 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 791
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 278
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 782
Points removed: 9
Total rows processed globally: 135925
Outlier count before clipping: 282

Skipping field time: unsupported OGR type: 10

Data retained: 747 rows after cleaning.
Trip max speed (3913.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 746
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 7
Rows after removal: 729
Points removed: 17
Total rows processed globally: 136654
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 20 rows after cleaning.
Trip max speed (20.73 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 19
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 10
Total rows processed globally: 136663
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 81 rows after cleaning.
Trip max speed (2.62 m/s) is within the cap of 2.78 m/s.
Initial rows: 80
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 79
Points removed: 1
Total rows processed globally: 136742
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 118 rows after cleaning.
Trip max speed (43.18 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 117
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 110
Points removed: 7
Total rows processed globally: 136852
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 1323 rows after cleaning.
Trip max speed (88.86 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 1322
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 678
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 1
Rows after removal: 1297
Points removed: 25
Total rows processed globally: 138149
Outlier count before clipping: 692

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (25.50 m/s).
File Sub_Trajectories_Cleaned/20080828022906/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 113 rows after cleaning.
Trip max speed (2.08 m/s) is within the cap of 2.78 m/s.
Initial rows: 112
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 111
Points removed: 1
Total rows processed globally: 138260
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 48 rows after cleaning.
Trip max speed (83.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 47
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 44
Points removed: 3
Total rows processed globally: 138304
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 147 rows after cleaning.
Trip max speed (285.27 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 146
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 4
Rows after removal: 140
Points removed: 6
Total rows processed globally: 138444
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 761 rows after cleaning.
Trip max speed (63.57 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 760
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 74
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 756
Points removed: 4
Total rows processed globally: 139200
Outlier count before clipping: 77

Skipping field time: unsupported OGR type: 10

Data retained: 225 rows after cleaning.
Trip max speed (69.19 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 224
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 4
Rows after removal: 216
Points removed: 8
Total rows processed globally: 139416
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 1735 rows after cleaning.
Trip max speed (81.00 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1734
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 125
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 1
Rows after removal: 1720
Points removed: 14
Total rows processed globally: 141136
Outlier count before clipping: 137

Skipping field time: unsupported OGR type: 10

Data retained: 316 rows after cleaning.
Trip max speed (206.55 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 315
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 309
Points removed: 6
Total rows processed globally: 141445
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (28.69 m/s).
File Sub_Trajectories_Cleaned/20080901000605/train_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 482 rows after cleaning.
Trip max speed (46.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 481
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 9
Rows after removal: 467
Points removed: 14
Total rows processed globally: 141912
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 106 rows after cleaning.
Trip max speed (28.21 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 105
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 103
Points removed: 2
Total rows processed globally: 142015
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 696 rows after cleaning.
Trip max speed (58.28 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 695
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 685
Points removed: 10
Total rows processed globally: 142700
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 51 rows after cleaning.
Trip max speed (19.43 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 50
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 47
Points removed: 3
Total rows processed globally: 142747
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 60 rows after cleaning.
Trip max speed (36.88 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 59
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 54
Points removed: 5
Total rows processed globally: 142801
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 39 rows after cleaning.
Trip max speed (381.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 38
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 33
Points removed: 5
Total rows processed globally: 142834
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 48 rows after cleaning.
Trip max speed (912.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 47
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 41
Points removed: 6
Total rows processed globally: 142875
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 11 rows after cleaning.
Trip max speed (2.67 m/s) is within the cap of 2.78 m/s.
Initial rows: 10
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 1
Total rows processed globally: 142884
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 335 rows after cleaning.
Trip max speed (71.12 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 334
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 44
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 1
Rows after removal: 320
Points removed: 14
Total rows processed globally: 143204
Outlier count before clipping: 56

Skipping field time: unsupported OGR type: 10

Data retained: 133 rows after cleaning.
Trip max speed (670.83 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 132
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 128
Points removed: 4
Total rows processed globally: 143332
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (23.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 55
Points removed: 3
Total rows processed globally: 143387
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 471 rows after cleaning.
Trip max speed (21.98 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 470
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 464
Points removed: 6
Total rows processed globally: 143851
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 17 rows after cleaning.
Trip max speed (6.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 16
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 14
Points removed: 2
Total rows processed globally: 143865
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (358.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 15
Points removed: 2
Total rows processed globally: 143880
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 69 rows after cleaning.
Trip max speed (10.11 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 68
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 66
Points removed: 2
Total rows processed globally: 143946
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (8.85 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 20
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 18
Points removed: 2
Total rows processed globally: 143964
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 593 rows after cleaning.
Trip max speed (56.49 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 592
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 577
Points removed: 15
Total rows processed globally: 144541
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 1746 rows after cleaning.
Trip max speed (43.96 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1745
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 357
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 0
Rows after removal: 1733
Points removed: 12
Total rows processed globally: 146274
Outlier count before clipping: 363

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.14 m/s).
File Sub_Trajectories_Cleaned/20080609014229/taxi_cleaned.geojson did not pass cleaning. Skipping.
Data discarded: mean speed too high (16.65 m/s).
File Sub_Trajectories_Cleaned/20080609014229/train_cleaned.geojson did not pass cleaning. Skipping.

Skipping field time: unsupported OGR type: 10

Data retained: 431 rows after cleaning.
Trip max speed (25.56 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 430
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 426
Points removed: 4
Total rows processed globally: 146700
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 185 rows after cleaning.
Trip max speed (54.51 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 184
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 174
Points removed: 10
Total rows processed globally: 146874
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 203 rows after cleaning.
Trip max speed (294.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 202
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 152
Very extreme outliers (>5x cap): 11
Rows after removal: 49
Points removed: 153
Total rows processed globally: 146923
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 149 rows after cleaning.
Trip max speed (23.20 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 148
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 146
Points removed: 2
Total rows processed globally: 147069
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (4.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 18
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 17
Points removed: 1
Total rows processed globally: 147086
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 410 rows after cleaning.
Trip max speed (33.40 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 409
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 398
Points removed: 11
Total rows processed globally: 147484
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 378 rows after cleaning.
Trip max speed (620.24 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 377
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 91
Extreme outliers (>2x cap): 178
Very extreme outliers (>5x cap): 10
Rows after removal: 198
Points removed: 179
Total rows processed globally: 147682
Outlier count before clipping: 100

Skipping field time: unsupported OGR type: 10

Data retained: 662 rows after cleaning.
Trip max speed (56.94 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 661
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 5
Rows after removal: 648
Points removed: 13
Total rows processed globally: 148330
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 916 rows after cleaning.
Trip max speed (67.20 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 915
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 149
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 904
Points removed: 11
Total rows processed globally: 149234
Outlier count before clipping: 155

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (30.35 m/s).
File Sub_Trajectories_Cleaned/20080606181635/train_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 266 rows after cleaning.
Trip max speed (8.14 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 265
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 262
Points removed: 3
Total rows processed globally: 149496
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 813 rows after cleaning.
Trip max speed (115.76 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 812
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 136
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 4
Rows after removal: 793
Points removed: 19
Total rows processed globally: 150289
Outlier count before clipping: 148

Skipping field time: unsupported OGR type: 10

Data retained: 31 rows after cleaning.
Trip max speed (11.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 30
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 3
Total rows processed globally: 150316
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 451 rows after cleaning.
Trip max speed (35.26 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 450
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 124
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 446
Points removed: 4
Total rows processed globally: 150762
Outlier count before clipping: 125

Skipping field time: unsupported OGR type: 10

Data retained: 266 rows after cleaning.
Trip max speed (29.72 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 265
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 258
Points removed: 7
Total rows processed globally: 151020
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 588 rows after cleaning.
Trip max speed (76.72 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 587
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 127
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 579
Points removed: 8
Total rows processed globally: 151599
Outlier count before clipping: 131

Skipping field time: unsupported OGR type: 10

Data retained: 218 rows after cleaning.
Trip max speed (35.38 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 217
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 3
Rows after removal: 209
Points removed: 8
Total rows processed globally: 151808
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.76 m/s).
File Sub_Trajectories_Cleaned/20090915122804/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 126 rows after cleaning.
Trip max speed (302.23 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 125
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 118
Points removed: 7
Total rows processed globally: 151926
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 461 rows after cleaning.
Trip max speed (36.57 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 460
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 453
Points removed: 7
Total rows processed globally: 152379
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 54 rows after cleaning.
Trip max speed (34.20 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 53
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 51
Points removed: 2
Total rows processed globally: 152430
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 72 rows after cleaning.
Trip max speed (389.29 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 71
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 68
Points removed: 3
Total rows processed globally: 152498
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 121 rows after cleaning.
Trip max speed (76.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 120
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 52
Very extreme outliers (>5x cap): 5
Rows after removal: 67
Points removed: 53
Total rows processed globally: 152565
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (103.58 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 17
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 13
Points removed: 4
Total rows processed globally: 152578
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 39 rows after cleaning.
Trip max speed (352.01 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 38
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 35
Points removed: 3
Total rows processed globally: 152613
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 40 rows after cleaning.
Trip max speed (43.64 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 39
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 37
Points removed: 2
Total rows processed globally: 152650
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 589 rows after cleaning.
Trip max speed (168.34 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 588
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 579
Points removed: 9
Total rows processed globally: 153229
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 15 rows after cleaning.
Trip max speed (11.63 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 14
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 12
Points removed: 2
Total rows processed globally: 153241
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (21.74 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 15
Points removed: 2
Total rows processed globally: 153256
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 185 rows after cleaning.
Trip max speed (16.41 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 184
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 183
Points removed: 1
Total rows processed globally: 153439
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 159 rows after cleaning.
Trip max speed (2018.69 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 158
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 154
Points removed: 4
Total rows processed globally: 153593
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 339 rows after cleaning.
Trip max speed (751.04 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 338
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 336
Points removed: 2
Total rows processed globally: 153929
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 483 rows after cleaning.
Trip max speed (35.37 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 482
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 474
Points removed: 8
Total rows processed globally: 154403
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (3.10 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 21
Points removed: 1
Total rows processed globally: 154424
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (3.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 18
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 17
Points removed: 1
Total rows processed globally: 154441
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 729 rows after cleaning.
Trip max speed (44.61 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 728
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 717
Points removed: 11
Total rows processed globally: 155158
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 914 rows after cleaning.
Trip max speed (34.29 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 913
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 0
Rows after removal: 901
Points removed: 12
Total rows processed globally: 156059
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 29 rows after cleaning.
Trip max speed (2.71 m/s) is within the cap of 2.78 m/s.
Initial rows: 28
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 1
Total rows processed globally: 156086
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 165 rows after cleaning.
Trip max speed (40.27 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 164
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 160
Points removed: 4
Total rows processed globally: 156246
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 118 rows after cleaning.
Trip max speed (136.13 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 117
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 113
Points removed: 4
Total rows processed globally: 156359
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 387 rows after cleaning.
Trip max speed (429.64 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 386
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 374
Points removed: 12
Total rows processed globally: 156733
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 390 rows after cleaning.
Trip max speed (39.93 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 389
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 378
Points removed: 11
Total rows processed globally: 157111
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (1.93 m/s) is within the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 1
Total rows processed globally: 157131
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 310 rows after cleaning.
Trip max speed (61.86 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 309
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 304
Points removed: 5
Total rows processed globally: 157435
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (34.33 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 45
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 43
Points removed: 2
Total rows processed globally: 157478
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 369 rows after cleaning.
Trip max speed (55.88 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 368
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 360
Points removed: 8
Total rows processed globally: 157838
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 64 rows after cleaning.
Trip max speed (4.47 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 63
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 62
Points removed: 1
Total rows processed globally: 157900
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 230 rows after cleaning.
Trip max speed (25.82 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 229
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 226
Points removed: 3
Total rows processed globally: 158126
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20080828101209/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 314 rows after cleaning.
Trip max speed (19.01 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 313
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 307
Points removed: 6
Total rows processed globally: 158433
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 164 rows after cleaning.
Trip max speed (25.44 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 163
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 156
Points removed: 7
Total rows processed globally: 158589
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 129 rows after cleaning.
Trip max speed (24.42 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 128
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 126
Points removed: 2
Total rows processed globally: 158715
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 98 rows after cleaning.
Trip max speed (1312.12 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 97
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 93
Points removed: 4
Total rows processed globally: 158808
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 1208 rows after cleaning.
Trip max speed (55.59 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1207
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 132
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 1
Rows after removal: 1182
Points removed: 25
Total rows processed globally: 159990
Outlier count before clipping: 151

Skipping field time: unsupported OGR type: 10

Data retained: 53 rows after cleaning.
Trip max speed (11.97 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 52
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 46
Points removed: 6
Total rows processed globally: 160036
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 743 rows after cleaning.
Trip max speed (323.67 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 742
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 110
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 5
Rows after removal: 717
Points removed: 25
Total rows processed globally: 160753
Outlier count before clipping: 116

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (319.80 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 45
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 27
Very extreme outliers (>5x cap): 3
Rows after removal: 17
Points removed: 28
Total rows processed globally: 160770
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 109 rows after cleaning.
Trip max speed (33.83 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 108
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 100
Points removed: 8
Total rows processed globally: 160870
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 25 rows after cleaning.
Trip max speed (4.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 24
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 23
Points removed: 1
Total rows processed globally: 160893
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 1579 rows after cleaning.
Trip max speed (126.68 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1578
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 42
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 4
Rows after removal: 1556
Points removed: 22
Total rows processed globally: 162449
Outlier count before clipping: 61

Skipping field time: unsupported OGR type: 10

Data retained: 113 rows after cleaning.
Trip max speed (16.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 112
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 109
Points removed: 3
Total rows processed globally: 162558
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 1135 rows after cleaning.
Trip max speed (74.54 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1134
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 53
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 1
Rows after removal: 1116
Points removed: 18
Total rows processed globally: 163674
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10

Data retained: 71 rows after cleaning.
Trip max speed (12.68 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 70
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 67
Points removed: 3
Total rows processed globally: 163741
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 593 rows after cleaning.
Trip max speed (312.77 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 592
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 200
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 585
Points removed: 7
Total rows processed globally: 164326
Outlier count before clipping: 203

Skipping field time: unsupported OGR type: 10

Data retained: 385 rows after cleaning.
Trip max speed (60.47 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 384
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 380
Points removed: 4
Total rows processed globally: 164706
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 83 rows after cleaning.
Trip max speed (10.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 82
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 79
Points removed: 3
Total rows processed globally: 164785
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 902 rows after cleaning.
Trip max speed (30.01 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 901
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 890
Points removed: 11
Total rows processed globally: 165675
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 260 rows after cleaning.
Trip max speed (73.96 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 259
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 251
Points removed: 8
Total rows processed globally: 165926
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 56 rows after cleaning.
Trip max speed (528.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 55
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 51
Points removed: 4
Total rows processed globally: 165977
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 608 rows after cleaning.
Trip max speed (88.76 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 607
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 5
Rows after removal: 600
Points removed: 7
Total rows processed globally: 166577
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 138 rows after cleaning.
Trip max speed (6.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 137
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 135
Points removed: 2
Total rows processed globally: 166712
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 433 rows after cleaning.
Trip max speed (74.61 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 432
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 420
Points removed: 12
Total rows processed globally: 167132
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 165 rows after cleaning.
Trip max speed (29.07 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 164
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 160
Points removed: 4
Total rows processed globally: 167292
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 10 rows after cleaning.
Trip max speed (1.34 m/s) is within the cap of 2.78 m/s.
Initial rows: 9
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 8
Points removed: 1
Total rows processed globally: 167300
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 1667 rows after cleaning.
Trip max speed (68.16 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1666
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 119
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 1
Rows after removal: 1645
Points removed: 21
Total rows processed globally: 168945
Outlier count before clipping: 139

Skipping field time: unsupported OGR type: 10

Data retained: 259 rows after cleaning.
Trip max speed (5253.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 258
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 4
Rows after removal: 244
Points removed: 14
Total rows processed globally: 169189
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 482 rows after cleaning.
Trip max speed (36.56 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 481
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 56
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 1
Rows after removal: 463
Points removed: 18
Total rows processed globally: 169652
Outlier count before clipping: 69

Skipping field time: unsupported OGR type: 10

Data retained: 598 rows after cleaning.
Trip max speed (43.97 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 597
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 205
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 594
Points removed: 3
Total rows processed globally: 170246
Outlier count before clipping: 206

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.39 m/s).
File Sub_Trajectories_Cleaned/20081011050330/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 296 rows after cleaning.
Trip max speed (10.28 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 295
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 290
Points removed: 5
Total rows processed globally: 170536
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (5.77 m/s) is within the cap of 6.94 m/s.
Initial rows: 12
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 170547
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 301 rows after cleaning.
Trip max speed (31.02 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 300
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 95
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 298
Points removed: 2
Total rows processed globally: 170845
Outlier count before clipping: 95

Skipping field time: unsupported OGR type: 10

Data retained: 215 rows after cleaning.
Trip max speed (51.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 214
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 210
Points removed: 4
Total rows processed globally: 171055
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (18.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 15
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 7
Points removed: 8
Total rows processed globally: 171062
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 436 rows after cleaning.
Trip max speed (21.49 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 435
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 430
Points removed: 5
Total rows processed globally: 171492
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 646 rows after cleaning.
Trip max speed (90.83 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 645
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 303
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 4
Rows after removal: 628
Points removed: 17
Total rows processed globally: 172120
Outlier count before clipping: 309

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (67.75 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 98
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 43
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 96
Points removed: 2
Total rows processed globally: 172216
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10

Data retained: 282 rows after cleaning.
Trip max speed (3063.84 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 281
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 275
Points removed: 6
Total rows processed globally: 172491
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 454 rows after cleaning.
Trip max speed (81.83 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 453
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 444
Points removed: 9
Total rows processed globally: 172935
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (6.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 2
Total rows processed globally: 172955
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 83 rows after cleaning.
Trip max speed (10.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 82
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 79
Points removed: 3
Total rows processed globally: 173034
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (2.72 m/s) is within the cap of 6.94 m/s.
Initial rows: 27
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 26
Points removed: 1
Total rows processed globally: 173060
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1087 rows after cleaning.
Trip max speed (77.69 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1086
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 3
Rows after removal: 1066
Points removed: 20
Total rows processed globally: 174126
Outlier count before clipping: 73

Skipping field time: unsupported OGR type: 10

Data retained: 418 rows after cleaning.
Trip max speed (51.24 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 417
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 62
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 414
Points removed: 3
Total rows processed globally: 174540
Outlier count before clipping: 63

Skipping field time: unsupported OGR type: 10

Data retained: 211 rows after cleaning.
Trip max speed (14.69 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 210
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 1
Rows after removal: 200
Points removed: 10
Total rows processed globally: 174740
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 164 rows after cleaning.
Trip max speed (22.13 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 163
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 4
Rows after removal: 153
Points removed: 10
Total rows processed globally: 174893
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 266 rows after cleaning.
Trip max speed (217.82 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 265
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 176
Very extreme outliers (>5x cap): 14
Rows after removal: 88
Points removed: 177
Total rows processed globally: 174981
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 61 rows after cleaning.
Trip max speed (2.64 m/s) is within the cap of 2.78 m/s.
Initial rows: 60
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 59
Points removed: 1
Total rows processed globally: 175040
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 454 rows after cleaning.
Trip max speed (41.35 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 453
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 447
Points removed: 6
Total rows processed globally: 175487
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 412 rows after cleaning.
Trip max speed (54.58 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 411
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 52
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 406
Points removed: 5
Total rows processed globally: 175893
Outlier count before clipping: 56

Skipping field time: unsupported OGR type: 10

Data retained: 24 rows after cleaning.
Trip max speed (4.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 23
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 22
Points removed: 1
Total rows processed globally: 175915
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 1659 rows after cleaning.
Trip max speed (87.32 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1658
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 172
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 1
Rows after removal: 1641
Points removed: 17
Total rows processed globally: 177556
Outlier count before clipping: 185

Skipping field time: unsupported OGR type: 10

Data retained: 218 rows after cleaning.
Trip max speed (42.18 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 217
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 212
Points removed: 5
Total rows processed globally: 177768
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 237 rows after cleaning.
Trip max speed (39.74 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 236
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 231
Points removed: 5
Total rows processed globally: 177999
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (1.66 m/s) is within the cap of 2.78 m/s.
Initial rows: 11
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 10
Points removed: 1
Total rows processed globally: 178009
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 29 rows after cleaning.
Trip max speed (5.59 m/s) is within the cap of 6.94 m/s.
Initial rows: 28
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 27
Points removed: 1
Total rows processed globally: 178036
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 43 rows after cleaning.
Trip max speed (6.92 m/s) is within the cap of 6.94 m/s.
Initial rows: 42
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 41
Points removed: 1
Total rows processed globally: 178077
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (154.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 17
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 15
Points removed: 2
Total rows processed globally: 178092
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 304 rows after cleaning.
Trip max speed (30.40 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 303
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 300
Points removed: 3
Total rows processed globally: 178392
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 202 rows after cleaning.
Trip max speed (9.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 201
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 198
Points removed: 3
Total rows processed globally: 178590
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 478 rows after cleaning.
Trip max speed (113.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 477
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 27
Very extreme outliers (>5x cap): 12
Rows after removal: 449
Points removed: 28
Total rows processed globally: 179039
Outlier count before clipping: 42

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (10.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 11
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 10
Points removed: 1
Total rows processed globally: 179049
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 183 rows after cleaning.
Trip max speed (77.83 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 182
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 73
Very extreme outliers (>5x cap): 4
Rows after removal: 108
Points removed: 74
Total rows processed globally: 179157
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 932 rows after cleaning.
Trip max speed (42.86 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 931
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 219
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 922
Points removed: 9
Total rows processed globally: 180079
Outlier count before clipping: 224

Skipping field time: unsupported OGR type: 10

Data retained: 138 rows after cleaning.
Trip max speed (35.16 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 137
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 82
Extreme outliers (>2x cap): 42
Very extreme outliers (>5x cap): 2
Rows after removal: 94
Points removed: 43
Total rows processed globally: 180173
Outlier count before clipping: 83

Skipping field time: unsupported OGR type: 10

Data retained: 178 rows after cleaning.
Trip max speed (14.42 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 177
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 172
Points removed: 5
Total rows processed globally: 180345
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 65 rows after cleaning.
Trip max speed (5.13 m/s) is within the cap of 6.94 m/s.
Initial rows: 64
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 63
Points removed: 1
Total rows processed globally: 180408
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 38 rows after cleaning.
Trip max speed (7.01 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 37
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 35
Points removed: 2
Total rows processed globally: 180443
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 181 rows after cleaning.
Trip max speed (40.77 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 180
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 178
Points removed: 2
Total rows processed globally: 180621
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 203 rows after cleaning.
Trip max speed (14.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 202
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 196
Points removed: 6
Total rows processed globally: 180817
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 1135 rows after cleaning.
Trip max speed (29.75 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1134
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 1129
Points removed: 5
Total rows processed globally: 181946
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (24.00 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 18
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 15
Points removed: 3
Total rows processed globally: 181961
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 124 rows after cleaning.
Trip max speed (23.45 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 123
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 121
Points removed: 2
Total rows processed globally: 182082
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 324 rows after cleaning.
Trip max speed (21.37 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 323
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 313
Points removed: 10
Total rows processed globally: 182395
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 217 rows after cleaning.
Trip max speed (13.14 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 216
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 215
Points removed: 1
Total rows processed globally: 182610
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 642 rows after cleaning.
Trip max speed (44.34 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 641
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 104
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 630
Points removed: 11
Total rows processed globally: 183240
Outlier count before clipping: 110

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.22 m/s).
File Sub_Trajectories_Cleaned/20081012003734/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 980 rows after cleaning.
Trip max speed (3550.15 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 979
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 7
Rows after removal: 962
Points removed: 17
Total rows processed globally: 184202
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 506 rows after cleaning.
Trip max speed (14.96 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 505
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 501
Points removed: 4
Total rows processed globally: 184703
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 41 rows after cleaning.
Trip max speed (3.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 40
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 39
Points removed: 1
Total rows processed globally: 184742
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 337 rows after cleaning.
Trip max speed (560.21 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 336
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 3
Rows after removal: 328
Points removed: 8
Total rows processed globally: 185070
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.87 m/s).
File Sub_Trajectories_Cleaned/20081108044227/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 114 rows after cleaning.
Trip max speed (108.24 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 113
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 23
Very extreme outliers (>5x cap): 2
Rows after removal: 89
Points removed: 24
Total rows processed globally: 185159
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (1.96 m/s) is within the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 97
Points removed: 1
Total rows processed globally: 185256
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 176 rows after cleaning.
Trip max speed (84.06 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 175
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 41
Very extreme outliers (>5x cap): 2
Rows after removal: 133
Points removed: 42
Total rows processed globally: 185389
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (15.47 m/s).
File Sub_Trajectories_Cleaned/20081213004659/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 376 rows after cleaning.
Trip max speed (34.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 375
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 5
Rows after removal: 366
Points removed: 9
Total rows processed globally: 185755
Outlier count before clipping: 65

Skipping field time: unsupported OGR type: 10

Data retained: 1372 rows after cleaning.
Trip max speed (33.76 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1371
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 129
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 1362
Points removed: 9
Total rows processed globally: 187117
Outlier count before clipping: 135

Skipping field time: unsupported OGR type: 10

Data retained: 195 rows after cleaning.
Trip max speed (44.40 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 194
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 4
Rows after removal: 185
Points removed: 9
Total rows processed globally: 187302
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 883 rows after cleaning.
Trip max speed (57.62 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 882
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 50
Extreme outliers (>2x cap): 29
Very extreme outliers (>5x cap): 15
Rows after removal: 852
Points removed: 30
Total rows processed globally: 188154
Outlier count before clipping: 74

Skipping field time: unsupported OGR type: 10

Data retained: 356 rows after cleaning.
Trip max speed (59.57 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 355
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 346
Points removed: 9
Total rows processed globally: 188500
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 362 rows after cleaning.
Trip max speed (180.29 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 361
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 75
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 4
Rows after removal: 351
Points removed: 10
Total rows processed globally: 188851
Outlier count before clipping: 79

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (0.90 m/s) is within the cap of 2.78 m/s.
Initial rows: 12
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 188862
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 236 rows after cleaning.
Trip max speed (423.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 235
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 152
Very extreme outliers (>5x cap): 16
Rows after removal: 82
Points removed: 153
Total rows processed globally: 188944
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 43 rows after cleaning.
Trip max speed (7.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 42
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 40
Points removed: 2
Total rows processed globally: 188984
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 127 rows after cleaning.
Trip max speed (20.09 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 126
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 121
Points removed: 5
Total rows processed globally: 189105
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 474 rows after cleaning.
Trip max speed (45.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 473
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 470
Points removed: 3
Total rows processed globally: 189575
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 102 rows after cleaning.
Trip max speed (17.30 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 101
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 98
Points removed: 3
Total rows processed globally: 189673
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20111024122939/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 753 rows after cleaning.
Trip max speed (35.07 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 752
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 746
Points removed: 6
Total rows processed globally: 190419
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 203 rows after cleaning.
Trip max speed (9.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 202
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 196
Points removed: 6
Total rows processed globally: 190615
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 299 rows after cleaning.
Trip max speed (161.36 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 298
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 291
Points removed: 7
Total rows processed globally: 190906
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 213 rows after cleaning.
Trip max speed (119.78 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 212
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 205
Points removed: 7
Total rows processed globally: 191111
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 401 rows after cleaning.
Trip max speed (52.53 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 400
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 393
Points removed: 7
Total rows processed globally: 191504
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 140 rows after cleaning.
Trip max speed (1685.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 139
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 4
Rows after removal: 134
Points removed: 5
Total rows processed globally: 191638
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 1000 rows after cleaning.
Trip max speed (61.36 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 999
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 1
Rows after removal: 982
Points removed: 17
Total rows processed globally: 192620
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10

Data retained: 129 rows after cleaning.
Trip max speed (31.43 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 128
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 5
Rows after removal: 117
Points removed: 11
Total rows processed globally: 192737
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 906 rows after cleaning.
Trip max speed (102.20 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 905
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 892
Points removed: 13
Total rows processed globally: 193629
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 544 rows after cleaning.
Trip max speed (44.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 543
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 534
Points removed: 9
Total rows processed globally: 194163
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 169 rows after cleaning.
Trip max speed (1616.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 168
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 58
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 5
Rows after removal: 149
Points removed: 19
Total rows processed globally: 194312
Outlier count before clipping: 65

Skipping field time: unsupported OGR type: 10

Data retained: 170 rows after cleaning.
Trip max speed (32.14 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 169
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 165
Points removed: 4
Total rows processed globally: 194477
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 1364 rows after cleaning.
Trip max speed (46.96 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1363
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 149
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 0
Rows after removal: 1346
Points removed: 17
Total rows processed globally: 195823
Outlier count before clipping: 162

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (16.70 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 17
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 14
Points removed: 3
Total rows processed globally: 195837
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 181 rows after cleaning.
Trip max speed (21.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 180
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 176
Points removed: 4
Total rows processed globally: 196013
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (9 rows).
File Sub_Trajectories_Cleaned/20080817175706/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 1144 rows after cleaning.
Trip max speed (86.59 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1143
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 95
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 3
Rows after removal: 1128
Points removed: 15
Total rows processed globally: 197141
Outlier count before clipping: 107

Skipping field time: unsupported OGR type: 10

Data retained: 263 rows after cleaning.
Trip max speed (7116.73 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 262
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 6
Rows after removal: 245
Points removed: 17
Total rows processed globally: 197386
Outlier count before clipping: 34

Skipping field time: unsupported OGR type: 10

Data retained: 456 rows after cleaning.
Trip max speed (70.40 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 455
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 32
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 1
Rows after removal: 445
Points removed: 10
Total rows processed globally: 197831
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 98 rows after cleaning.
Trip max speed (4.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 97
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 96
Points removed: 1
Total rows processed globally: 197927
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 684 rows after cleaning.
Trip max speed (501.73 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 683
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 91
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 5
Rows after removal: 665
Points removed: 18
Total rows processed globally: 198592
Outlier count before clipping: 101

Skipping field time: unsupported OGR type: 10

Data retained: 131 rows after cleaning.
Trip max speed (39.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 130
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 5
Rows after removal: 116
Points removed: 14
Total rows processed globally: 198708
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 589 rows after cleaning.
Trip max speed (36.75 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 588
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 584
Points removed: 4
Total rows processed globally: 199292
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 825 rows after cleaning.
Trip max speed (44.64 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 824
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 2
Rows after removal: 809
Points removed: 15
Total rows processed globally: 200101
Outlier count before clipping: 46

Skipping field time: unsupported OGR type: 10

Data retained: 632 rows after cleaning.
Trip max speed (33.01 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 631
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 33
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 7
Rows after removal: 611
Points removed: 20
Total rows processed globally: 200712
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 479 rows after cleaning.
Trip max speed (58.65 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 478
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 476
Points removed: 2
Total rows processed globally: 201188
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 431 rows after cleaning.
Trip max speed (95.78 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 430
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 100
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 418
Points removed: 12
Total rows processed globally: 201606
Outlier count before clipping: 108

Skipping field time: unsupported OGR type: 10

Data retained: 80 rows after cleaning.
Trip max speed (94.09 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 79
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 72
Points removed: 7
Total rows processed globally: 201678
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 399 rows after cleaning.
Trip max speed (1628.14 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 398
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 102
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 3
Rows after removal: 382
Points removed: 16
Total rows processed globally: 202060
Outlier count before clipping: 114

Skipping field time: unsupported OGR type: 10

Data retained: 227 rows after cleaning.
Trip max speed (2.14 m/s) is within the cap of 2.78 m/s.
Initial rows: 226
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 225
Points removed: 1
Total rows processed globally: 202285
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 403 rows after cleaning.
Trip max speed (76.23 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 402
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 73
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 397
Points removed: 5
Total rows processed globally: 202682
Outlier count before clipping: 73

Skipping field time: unsupported OGR type: 10

Data retained: 357 rows after cleaning.
Trip max speed (27.53 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 356
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 348
Points removed: 8
Total rows processed globally: 203030
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 112 rows after cleaning.
Trip max speed (14.69 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 111
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 110
Points removed: 1
Total rows processed globally: 203140
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (33.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 14
Points removed: 7
Total rows processed globally: 203154
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (71.91 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 61
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 26
Very extreme outliers (>5x cap): 2
Rows after removal: 34
Points removed: 27
Total rows processed globally: 203188
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 292 rows after cleaning.
Trip max speed (27.04 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 291
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 285
Points removed: 6
Total rows processed globally: 203473
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 22 rows after cleaning.
Trip max speed (3.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 21
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 1
Total rows processed globally: 203493
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 333 rows after cleaning.
Trip max speed (9.79 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 332
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 327
Points removed: 5
Total rows processed globally: 203820
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 404 rows after cleaning.
Trip max speed (108.50 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 403
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 1
Rows after removal: 390
Points removed: 13
Total rows processed globally: 204210
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 92 rows after cleaning.
Trip max speed (21.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 91
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 87
Points removed: 4
Total rows processed globally: 204297
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 106 rows after cleaning.
Trip max speed (152.84 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 105
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 90
Points removed: 15
Total rows processed globally: 204387
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 178 rows after cleaning.
Trip max speed (189.88 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 177
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 9
Rows after removal: 158
Points removed: 19
Total rows processed globally: 204545
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 438 rows after cleaning.
Trip max speed (54.92 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 437
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 431
Points removed: 6
Total rows processed globally: 204976
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 54 rows after cleaning.
Trip max speed (3.57 m/s) is within the cap of 11.11 m/s.
Initial rows: 53
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 52
Points removed: 1
Total rows processed globally: 205028
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 549 rows after cleaning.
Trip max speed (88.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 548
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 60
Extreme outliers (>2x cap): 134
Very extreme outliers (>5x cap): 29
Rows after removal: 413
Points removed: 135
Total rows processed globally: 205441
Outlier count before clipping: 94

Skipping field time: unsupported OGR type: 10

Data retained: 1427 rows after cleaning.
Trip max speed (58.99 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1426
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 135
Extreme outliers (>2x cap): 25
Very extreme outliers (>5x cap): 1
Rows after removal: 1400
Points removed: 26
Total rows processed globally: 206841
Outlier count before clipping: 160

Skipping field time: unsupported OGR type: 10

Data retained: 229 rows after cleaning.
Trip max speed (89.84 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 228
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 7
Rows after removal: 213
Points removed: 15
Total rows processed globally: 207054
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 629 rows after cleaning.
Trip max speed (46.99 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 628
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 622
Points removed: 6
Total rows processed globally: 207676
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 148 rows after cleaning.
Trip max speed (1520.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 147
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 143
Points removed: 4
Total rows processed globally: 207819
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 255 rows after cleaning.
Trip max speed (36.64 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 254
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 250
Points removed: 4
Total rows processed globally: 208069
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (1.72 m/s) is within the cap of 2.78 m/s.
Initial rows: 11
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 10
Points removed: 1
Total rows processed globally: 208079
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 296 rows after cleaning.
Trip max speed (25.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 295
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 293
Points removed: 2
Total rows processed globally: 208372
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 446 rows after cleaning.
Trip max speed (1828.99 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 445
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 8
Rows after removal: 427
Points removed: 18
Total rows processed globally: 208799
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 326 rows after cleaning.
Trip max speed (71.88 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 325
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 315
Points removed: 10
Total rows processed globally: 209114
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 52 rows after cleaning.
Trip max speed (25.69 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 51
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 49
Points removed: 2
Total rows processed globally: 209163
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 286 rows after cleaning.
Trip max speed (27.56 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 285
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 281
Points removed: 4
Total rows processed globally: 209444
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 534 rows after cleaning.
Trip max speed (30.27 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 533
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 54
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 530
Points removed: 3
Total rows processed globally: 209974
Outlier count before clipping: 56

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (7.73 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 95
Points removed: 3
Total rows processed globally: 210069
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20081210003239/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 300 rows after cleaning.
Trip max speed (50.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 299
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 151
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 293
Points removed: 6
Total rows processed globally: 210362
Outlier count before clipping: 155

Skipping field time: unsupported OGR type: 10

Data retained: 80 rows after cleaning.
Trip max speed (14.03 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 79
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 78
Points removed: 1
Total rows processed globally: 210440
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 83 rows after cleaning.
Trip max speed (29.08 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 82
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 79
Points removed: 3
Total rows processed globally: 210519
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 807 rows after cleaning.
Trip max speed (101.51 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 806
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 51
Extreme outliers (>2x cap): 29
Very extreme outliers (>5x cap): 4
Rows after removal: 776
Points removed: 30
Total rows processed globally: 211295
Outlier count before clipping: 83

Skipping field time: unsupported OGR type: 10

Data retained: 767 rows after cleaning.
Trip max speed (51.85 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 766
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 49
Extreme outliers (>2x cap): 21
Very extreme outliers (>5x cap): 9
Rows after removal: 744
Points removed: 22
Total rows processed globally: 212039
Outlier count before clipping: 67

Skipping field time: unsupported OGR type: 10

Data retained: 453 rows after cleaning.
Trip max speed (59.22 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 452
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 37
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 440
Points removed: 12
Total rows processed globally: 212479
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 75 rows after cleaning.
Trip max speed (29.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 74
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 70
Points removed: 4
Total rows processed globally: 212549
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.09 m/s).
File Sub_Trajectories_Cleaned/20080508093034/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 358 rows after cleaning.
Trip max speed (49.57 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 357
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 2
Rows after removal: 348
Points removed: 9
Total rows processed globally: 212897
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 1066 rows after cleaning.
Trip max speed (222.34 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1065
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 71
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 4
Rows after removal: 1051
Points removed: 14
Total rows processed globally: 213948
Outlier count before clipping: 81

Skipping field time: unsupported OGR type: 10

Data retained: 120 rows after cleaning.
Trip max speed (1722.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 119
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 113
Points removed: 6
Total rows processed globally: 214061
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 535 rows after cleaning.
Trip max speed (32.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 534
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 0
Rows after removal: 522
Points removed: 12
Total rows processed globally: 214583
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 509 rows after cleaning.
Trip max speed (62.97 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 508
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 151
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 497
Points removed: 11
Total rows processed globally: 215080
Outlier count before clipping: 159

Skipping field time: unsupported OGR type: 10

Data retained: 96 rows after cleaning.
Trip max speed (42.40 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 95
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 90
Points removed: 5
Total rows processed globally: 215170
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 152 rows after cleaning.
Trip max speed (7.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 151
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 148
Points removed: 3
Total rows processed globally: 215318
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 1051 rows after cleaning.
Trip max speed (218.06 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1050
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 37
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 5
Rows after removal: 1036
Points removed: 14
Total rows processed globally: 216354
Outlier count before clipping: 67

Skipping field time: unsupported OGR type: 10

Data retained: 310 rows after cleaning.
Trip max speed (22.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 309
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 3
Rows after removal: 297
Points removed: 12
Total rows processed globally: 216651
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 274 rows after cleaning.
Trip max speed (351.84 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 273
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 270
Points removed: 3
Total rows processed globally: 216921
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 15 rows after cleaning.
Trip max speed (145.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 14
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 7
Points removed: 7
Total rows processed globally: 216928
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 367 rows after cleaning.
Trip max speed (99.94 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 366
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 32
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 2
Rows after removal: 352
Points removed: 14
Total rows processed globally: 217280
Outlier count before clipping: 44

Skipping field time: unsupported OGR type: 10

Data retained: 76 rows after cleaning.
Trip max speed (7.62 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 75
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 72
Points removed: 3
Total rows processed globally: 217352
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 1204 rows after cleaning.
Trip max speed (90.65 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1203
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 93
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 2
Rows after removal: 1187
Points removed: 16
Total rows processed globally: 218539
Outlier count before clipping: 106

Skipping field time: unsupported OGR type: 10

Data retained: 335 rows after cleaning.
Trip max speed (3989.70 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 334
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 329
Points removed: 5
Total rows processed globally: 218868
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 17 rows after cleaning.
Trip max speed (45.18 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 16
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 14
Points removed: 2
Total rows processed globally: 218882
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (29.57 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 27
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 22
Points removed: 5
Total rows processed globally: 218904
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 101 rows after cleaning.
Trip max speed (33.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 100
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 5
Rows after removal: 93
Points removed: 7
Total rows processed globally: 218997
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 271 rows after cleaning.
Trip max speed (46.09 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 270
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 266
Points removed: 4
Total rows processed globally: 219263
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (2.17 m/s) is within the cap of 2.78 m/s.
Initial rows: 33
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 32
Points removed: 1
Total rows processed globally: 219295
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 316 rows after cleaning.
Trip max speed (21.21 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 315
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 310
Points removed: 5
Total rows processed globally: 219605
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 97 rows after cleaning.
Trip max speed (39.48 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 96
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 93
Points removed: 3
Total rows processed globally: 219698
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 586 rows after cleaning.
Trip max speed (43.01 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 585
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 581
Points removed: 4
Total rows processed globally: 220279
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 329 rows after cleaning.
Trip max speed (37.85 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 328
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 86
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 324
Points removed: 4
Total rows processed globally: 220603
Outlier count before clipping: 89

Skipping field time: unsupported OGR type: 10

Data retained: 371 rows after cleaning.
Trip max speed (42.79 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 370
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 364
Points removed: 6
Total rows processed globally: 220967
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 287 rows after cleaning.
Trip max speed (35.53 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 286
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 273
Points removed: 13
Total rows processed globally: 221240
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 162 rows after cleaning.
Trip max speed (28.64 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 161
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 155
Points removed: 6
Total rows processed globally: 221395
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 457 rows after cleaning.
Trip max speed (25.00 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 456
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 450
Points removed: 6
Total rows processed globally: 221845
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 10 rows after cleaning.
Trip max speed (3.79 m/s) is within the cap of 11.11 m/s.
Initial rows: 9
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 8
Points removed: 1
Total rows processed globally: 221853
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 37 rows after cleaning.
Trip max speed (19.37 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 36
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 34
Points removed: 2
Total rows processed globally: 221887
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 767 rows after cleaning.
Trip max speed (65.13 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 766
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 4
Rows after removal: 748
Points removed: 18
Total rows processed globally: 222635
Outlier count before clipping: 36

Skipping field time: unsupported OGR type: 10

Data retained: 649 rows after cleaning.
Trip max speed (51.12 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 648
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 51
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 639
Points removed: 9
Total rows processed globally: 223274
Outlier count before clipping: 57

Skipping field time: unsupported OGR type: 10

Data retained: 312 rows after cleaning.
Trip max speed (27.71 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 311
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 5
Rows after removal: 298
Points removed: 13
Total rows processed globally: 223572
Outlier count before clipping: 47

Skipping field time: unsupported OGR type: 10

Data retained: 431 rows after cleaning.
Trip max speed (30.02 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 430
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 421
Points removed: 9
Total rows processed globally: 223993
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.79 m/s).
File Sub_Trajectories_Cleaned/20090927113103/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 138 rows after cleaning.
Trip max speed (2081.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 137
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 4
Rows after removal: 129
Points removed: 8
Total rows processed globally: 224122
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 404 rows after cleaning.
Trip max speed (55.17 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 403
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 7
Rows after removal: 392
Points removed: 11
Total rows processed globally: 224514
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.67 m/s).
File Sub_Trajectories_Cleaned/20090910011022/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 72 rows after cleaning.
Trip max speed (2084.56 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 71
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 65
Points removed: 6
Total rows processed globally: 224579
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 111 rows after cleaning.
Trip max speed (13.45 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 110
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 109
Points removed: 1
Total rows processed globally: 224688
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 149 rows after cleaning.
Trip max speed (23.43 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 148
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 143
Points removed: 5
Total rows processed globally: 224831
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 937 rows after cleaning.
Trip max speed (39.77 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 936
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 1
Rows after removal: 920
Points removed: 16
Total rows processed globally: 225751
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10

Data retained: 468 rows after cleaning.
Trip max speed (41.12 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 467
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 462
Points removed: 5
Total rows processed globally: 226213
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 178 rows after cleaning.
Trip max speed (1698.78 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 177
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 4
Rows after removal: 167
Points removed: 10
Total rows processed globally: 226380
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 547 rows after cleaning.
Trip max speed (26.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 546
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 544
Points removed: 2
Total rows processed globally: 226924
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 537 rows after cleaning.
Trip max speed (26.96 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 536
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 528
Points removed: 8
Total rows processed globally: 227452
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (1319.78 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 61
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 58
Points removed: 3
Total rows processed globally: 227510
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 390 rows after cleaning.
Trip max speed (30.92 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 389
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 383
Points removed: 6
Total rows processed globally: 227893
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 343 rows after cleaning.
Trip max speed (19.57 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 342
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 97
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 341
Points removed: 1
Total rows processed globally: 228234
Outlier count before clipping: 97

Skipping field time: unsupported OGR type: 10

Data retained: 38 rows after cleaning.
Trip max speed (1468.15 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 37
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 35
Points removed: 2
Total rows processed globally: 228269
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (13.17 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 1
Total rows processed globally: 228285
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 136 rows after cleaning.
Trip max speed (44.78 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 135
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 131
Points removed: 4
Total rows processed globally: 228416
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.17 m/s).
File Sub_Trajectories_Cleaned/20090825112752/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 486 rows after cleaning.
Trip max speed (56.91 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 485
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 481
Points removed: 4
Total rows processed globally: 228897
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 32 rows after cleaning.
Trip max speed (4.29 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 31
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 30
Points removed: 1
Total rows processed globally: 228927
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 237 rows after cleaning.
Trip max speed (48.88 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 236
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 115
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 232
Points removed: 4
Total rows processed globally: 229159
Outlier count before clipping: 118

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (3548.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 17
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 15
Points removed: 2
Total rows processed globally: 229174
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1104 rows after cleaning.
Trip max speed (90.16 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1103
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 55
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 1088
Points removed: 15
Total rows processed globally: 230262
Outlier count before clipping: 65

Skipping field time: unsupported OGR type: 10

Data retained: 404 rows after cleaning.
Trip max speed (34.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 403
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 4
Rows after removal: 391
Points removed: 12
Total rows processed globally: 230653
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (12.41 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 1
Total rows processed globally: 230669
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 42 rows after cleaning.
Trip max speed (376.71 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 41
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 39
Points removed: 2
Total rows processed globally: 230708
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 98 rows after cleaning.
Trip max speed (616.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 97
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 4
Rows after removal: 92
Points removed: 5
Total rows processed globally: 230800
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 85 rows after cleaning.
Trip max speed (14.95 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 84
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 82
Points removed: 2
Total rows processed globally: 230882
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 24 rows after cleaning.
Trip max speed (49.89 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 23
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 20
Points removed: 3
Total rows processed globally: 230902
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 155 rows after cleaning.
Trip max speed (25.60 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 154
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 150
Points removed: 4
Total rows processed globally: 231052
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 183 rows after cleaning.
Trip max speed (45.67 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 182
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 174
Points removed: 8
Total rows processed globally: 231226
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 433 rows after cleaning.
Trip max speed (29.38 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 432
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 424
Points removed: 8
Total rows processed globally: 231650
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 803 rows after cleaning.
Trip max speed (24.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 802
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 794
Points removed: 8
Total rows processed globally: 232444
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (20.24 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 18
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 17
Points removed: 1
Total rows processed globally: 232461
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 11 rows after cleaning.
Trip max speed (122.55 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 10
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 8
Points removed: 2
Total rows processed globally: 232469
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 998 rows after cleaning.
Trip max speed (67.79 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 997
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 6
Rows after removal: 976
Points removed: 21
Total rows processed globally: 233445
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 419 rows after cleaning.
Trip max speed (55.12 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 418
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 412
Points removed: 6
Total rows processed globally: 233857
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 793 rows after cleaning.
Trip max speed (37.97 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 792
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 1
Rows after removal: 767
Points removed: 25
Total rows processed globally: 234624
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 249 rows after cleaning.
Trip max speed (29.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 248
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 242
Points removed: 6
Total rows processed globally: 234866
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 992 rows after cleaning.
Trip max speed (36.14 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 991
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 979
Points removed: 12
Total rows processed globally: 235845
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (21.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 61
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 59
Points removed: 2
Total rows processed globally: 235904
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 668 rows after cleaning.
Trip max speed (53.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 667
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 661
Points removed: 6
Total rows processed globally: 236565
Outlier count before clipping: 51

Skipping field time: unsupported OGR type: 10

Data retained: 52 rows after cleaning.
Trip max speed (5.22 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 51
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 50
Points removed: 1
Total rows processed globally: 236615
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 360 rows after cleaning.
Trip max speed (49.54 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 359
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 5
Rows after removal: 348
Points removed: 11
Total rows processed globally: 236963
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (19.05 m/s).
File Sub_Trajectories_Cleaned/20090918103558/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 26 rows after cleaning.
Trip max speed (1.62 m/s) is within the cap of 2.78 m/s.
Initial rows: 25
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 24
Points removed: 1
Total rows processed globally: 236987
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 138 rows after cleaning.
Trip max speed (33.98 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 137
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 134
Points removed: 3
Total rows processed globally: 237121
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 103 rows after cleaning.
Trip max speed (10.84 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 102
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 99
Points removed: 3
Total rows processed globally: 237220
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 606 rows after cleaning.
Trip max speed (32.97 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 605
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 596
Points removed: 9
Total rows processed globally: 237816
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 1452 rows after cleaning.
Trip max speed (114.53 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1451
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 45
Very extreme outliers (>5x cap): 31
Rows after removal: 1405
Points removed: 46
Total rows processed globally: 239221
Outlier count before clipping: 78

Skipping field time: unsupported OGR type: 10

Data retained: 1073 rows after cleaning.
Trip max speed (1272.29 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1072
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 298
Extreme outliers (>2x cap): 639
Very extreme outliers (>5x cap): 21
Rows after removal: 432
Points removed: 640
Total rows processed globally: 239653
Outlier count before clipping: 324

Skipping field time: unsupported OGR type: 10

Data retained: 194 rows after cleaning.
Trip max speed (301.54 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 193
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 184
Points removed: 9
Total rows processed globally: 239837
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 1018 rows after cleaning.
Trip max speed (263.93 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1017
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 58
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 9
Rows after removal: 998
Points removed: 19
Total rows processed globally: 240835
Outlier count before clipping: 72

Skipping field time: unsupported OGR type: 10

Data retained: 111 rows after cleaning.
Trip max speed (16.27 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 110
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 108
Points removed: 2
Total rows processed globally: 240943
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 112 rows after cleaning.
Trip max speed (112.63 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 111
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 23
Very extreme outliers (>5x cap): 4
Rows after removal: 87
Points removed: 24
Total rows processed globally: 241030
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (18.82 m/s).
File Sub_Trajectories_Cleaned/20081201163736/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 329 rows after cleaning.
Trip max speed (18.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 328
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 319
Points removed: 9
Total rows processed globally: 241349
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 123 rows after cleaning.
Trip max speed (81.27 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 122
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 68
Very extreme outliers (>5x cap): 4
Rows after removal: 53
Points removed: 69
Total rows processed globally: 241402
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 401 rows after cleaning.
Trip max speed (37.45 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 400
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 390
Points removed: 10
Total rows processed globally: 241792
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 524 rows after cleaning.
Trip max speed (72.34 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 523
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 37
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 511
Points removed: 12
Total rows processed globally: 242303
Outlier count before clipping: 72

Skipping field time: unsupported OGR type: 10

Data retained: 119 rows after cleaning.
Trip max speed (29.58 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 118
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 110
Points removed: 8
Total rows processed globally: 242413
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 476 rows after cleaning.
Trip max speed (25.32 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 475
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 469
Points removed: 6
Total rows processed globally: 242882
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 19 rows after cleaning.
Trip max speed (1.93 m/s) is within the cap of 2.78 m/s.
Initial rows: 18
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 17
Points removed: 1
Total rows processed globally: 242899
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 202 rows after cleaning.
Trip max speed (36.47 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 201
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 199
Points removed: 2
Total rows processed globally: 243098
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 374 rows after cleaning.
Trip max speed (381.83 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 373
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 52
Very extreme outliers (>5x cap): 6
Rows after removal: 320
Points removed: 53
Total rows processed globally: 243418
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (88.35 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 4
Rows after removal: 92
Points removed: 6
Total rows processed globally: 243510
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20070428134038/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 116 rows after cleaning.
Trip max speed (144.01 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 115
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 3
Rows after removal: 101
Points removed: 14
Total rows processed globally: 243611
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (3.74 m/s) is within the cap of 6.94 m/s.
Initial rows: 33
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 32
Points removed: 1
Total rows processed globally: 243643
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 307 rows after cleaning.
Trip max speed (79.22 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 306
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 7
Rows after removal: 293
Points removed: 13
Total rows processed globally: 243936
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 799 rows after cleaning.
Trip max speed (34.20 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 798
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 4
Rows after removal: 784
Points removed: 14
Total rows processed globally: 244720
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 630 rows after cleaning.
Trip max speed (128.69 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 629
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 617
Points removed: 12
Total rows processed globally: 245337
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 209 rows after cleaning.
Trip max speed (61.03 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 208
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 200
Points removed: 8
Total rows processed globally: 245537
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 440 rows after cleaning.
Trip max speed (1467.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 439
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 11
Rows after removal: 423
Points removed: 16
Total rows processed globally: 245960
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 17 rows after cleaning.
Trip max speed (11.19 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 16
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 15
Points removed: 1
Total rows processed globally: 245975
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 130 rows after cleaning.
Trip max speed (62.32 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 129
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 86
Very extreme outliers (>5x cap): 2
Rows after removal: 42
Points removed: 87
Total rows processed globally: 246017
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20090619093937/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 37 rows after cleaning.
Trip max speed (2.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 36
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 35
Points removed: 1
Total rows processed globally: 246052
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (17.98 m/s).
File Sub_Trajectories_Cleaned/20090914142328/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 136 rows after cleaning.
Trip max speed (3478.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 135
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 126
Points removed: 9
Total rows processed globally: 246178
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 649 rows after cleaning.
Trip max speed (427.84 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 648
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 6
Rows after removal: 637
Points removed: 11
Total rows processed globally: 246815
Outlier count before clipping: 44

Skipping field time: unsupported OGR type: 10

Data retained: 333 rows after cleaning.
Trip max speed (39.42 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 332
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 36
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 327
Points removed: 5
Total rows processed globally: 247142
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 232 rows after cleaning.
Trip max speed (11.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 231
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 227
Points removed: 4
Total rows processed globally: 247369
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 577 rows after cleaning.
Trip max speed (47.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 576
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 565
Points removed: 11
Total rows processed globally: 247934
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (10.59 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 2
Total rows processed globally: 247954
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.65 m/s).
File Sub_Trajectories_Cleaned/20080820120327/taxi_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 64 rows after cleaning.
Trip max speed (2423.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 63
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 60
Points removed: 3
Total rows processed globally: 248014
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 395 rows after cleaning.
Trip max speed (1852.42 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 394
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 5
Rows after removal: 382
Points removed: 12
Total rows processed globally: 248396
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 335 rows after cleaning.
Trip max speed (190.14 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 334
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 7
Rows after removal: 324
Points removed: 10
Total rows processed globally: 248720
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 238 rows after cleaning.
Trip max speed (12.45 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 237
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 236
Points removed: 1
Total rows processed globally: 248956
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 30 rows after cleaning.
Trip max speed (2.46 m/s) is within the cap of 2.78 m/s.
Initial rows: 29
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 28
Points removed: 1
Total rows processed globally: 248984
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 762 rows after cleaning.
Trip max speed (86.03 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 761
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 749
Points removed: 12
Total rows processed globally: 249733
Outlier count before clipping: 39

Skipping field time: unsupported OGR type: 10

Data retained: 191 rows after cleaning.
Trip max speed (41.47 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 190
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 182
Points removed: 8
Total rows processed globally: 249915
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 383 rows after cleaning.
Trip max speed (64.02 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 382
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 1
Rows after removal: 372
Points removed: 10
Total rows processed globally: 250287
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (3349.71 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 54
Points removed: 4
Total rows processed globally: 250341
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 482 rows after cleaning.
Trip max speed (45.73 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 481
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 474
Points removed: 7
Total rows processed globally: 250815
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 46 rows after cleaning.
Trip max speed (12.30 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 45
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 44
Points removed: 1
Total rows processed globally: 250859
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 109 rows after cleaning.
Trip max speed (202.62 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 108
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 2
Rows after removal: 100
Points removed: 8
Total rows processed globally: 250959
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (74.36 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 98
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 35
Very extreme outliers (>5x cap): 5
Rows after removal: 62
Points removed: 36
Total rows processed globally: 251021
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 352 rows after cleaning.
Trip max speed (24.82 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 351
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 338
Points removed: 13
Total rows processed globally: 251359
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 596 rows after cleaning.
Trip max speed (43.48 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 595
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 3
Rows after removal: 580
Points removed: 15
Total rows processed globally: 251939
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 63 rows after cleaning.
Trip max speed (25.17 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 62
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 58
Points removed: 4
Total rows processed globally: 251997
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 1077 rows after cleaning.
Trip max speed (106.85 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1076
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 49
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 2
Rows after removal: 1059
Points removed: 17
Total rows processed globally: 253056
Outlier count before clipping: 64

Skipping field time: unsupported OGR type: 10

Data retained: 168 rows after cleaning.
Trip max speed (12.45 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 167
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 161
Points removed: 6
Total rows processed globally: 253217
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 240 rows after cleaning.
Trip max speed (43.64 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 239
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 56
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 236
Points removed: 3
Total rows processed globally: 253453
Outlier count before clipping: 58

Skipping field time: unsupported OGR type: 10

Data retained: 10 rows after cleaning.
Trip max speed (4.01 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 9
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 8
Points removed: 1
Total rows processed globally: 253461
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 687 rows after cleaning.
Trip max speed (46.89 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 686
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 681
Points removed: 5
Total rows processed globally: 254142
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 404 rows after cleaning.
Trip max speed (1707.95 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 403
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 6
Rows after removal: 387
Points removed: 16
Total rows processed globally: 254529
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 495 rows after cleaning.
Trip max speed (156.98 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 494
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 68
Extreme outliers (>2x cap): 44
Very extreme outliers (>5x cap): 7
Rows after removal: 449
Points removed: 45
Total rows processed globally: 254978
Outlier count before clipping: 80

Skipping field time: unsupported OGR type: 10

Data retained: 45 rows after cleaning.
Trip max speed (7.76 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 44
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 40
Points removed: 4
Total rows processed globally: 255018
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 55 rows after cleaning.
Trip max speed (1690.49 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 54
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 49
Points removed: 5
Total rows processed globally: 255067
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 438 rows after cleaning.
Trip max speed (66.71 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 437
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 425
Points removed: 12
Total rows processed globally: 255492
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 11 rows after cleaning.
Trip max speed (0.18 m/s) is within the cap of 2.78 m/s.
Initial rows: 10
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 1
Total rows processed globally: 255501
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 475 rows after cleaning.
Trip max speed (89.08 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 474
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 461
Points removed: 13
Total rows processed globally: 255962
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 120 rows after cleaning.
Trip max speed (1708.92 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 119
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 113
Points removed: 6
Total rows processed globally: 256075
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 550 rows after cleaning.
Trip max speed (59.89 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 549
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 544
Points removed: 5
Total rows processed globally: 256619
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 227 rows after cleaning.
Trip max speed (1673.59 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 226
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 221
Points removed: 5
Total rows processed globally: 256840
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 507 rows after cleaning.
Trip max speed (31.69 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 506
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 498
Points removed: 8
Total rows processed globally: 257338
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 14 rows after cleaning.
Trip max speed (5.59 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 13
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 2
Total rows processed globally: 257349
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 331 rows after cleaning.
Trip max speed (38.30 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 330
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 323
Points removed: 7
Total rows processed globally: 257672
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 491 rows after cleaning.
Trip max speed (108.07 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 490
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 3
Rows after removal: 477
Points removed: 13
Total rows processed globally: 258149
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 110 rows after cleaning.
Trip max speed (4.42 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 109
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 108
Points removed: 1
Total rows processed globally: 258257
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 1256 rows after cleaning.
Trip max speed (354.25 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1255
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 98
Extreme outliers (>2x cap): 67
Very extreme outliers (>5x cap): 11
Rows after removal: 1187
Points removed: 68
Total rows processed globally: 259444
Outlier count before clipping: 147

Skipping field time: unsupported OGR type: 10

Data retained: 221 rows after cleaning.
Trip max speed (122.98 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 220
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 4
Rows after removal: 210
Points removed: 10
Total rows processed globally: 259654
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 290 rows after cleaning.
Trip max speed (15.01 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 289
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 288
Points removed: 1
Total rows processed globally: 259942
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 101 rows after cleaning.
Trip max speed (12.30 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 100
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 97
Points removed: 3
Total rows processed globally: 260039
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 443 rows after cleaning.
Trip max speed (119.18 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 442
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 42
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 430
Points removed: 12
Total rows processed globally: 260469
Outlier count before clipping: 52

Skipping field time: unsupported OGR type: 10

Data retained: 26 rows after cleaning.
Trip max speed (7.76 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 25
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 21
Points removed: 4
Total rows processed globally: 260490
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 157 rows after cleaning.
Trip max speed (88.29 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 156
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 125
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 5
Rows after removal: 145
Points removed: 11
Total rows processed globally: 260635
Outlier count before clipping: 124

Skipping field time: unsupported OGR type: 10

Data retained: 36 rows after cleaning.
Trip max speed (20.96 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 35
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 34
Points removed: 1
Total rows processed globally: 260669
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (25.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 55
Points removed: 3
Total rows processed globally: 260724
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 485 rows after cleaning.
Trip max speed (77.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 484
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 3
Rows after removal: 473
Points removed: 11
Total rows processed globally: 261197
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 443 rows after cleaning.
Trip max speed (16.53 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 442
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 431
Points removed: 11
Total rows processed globally: 261628
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 187 rows after cleaning.
Trip max speed (24.83 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 186
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 180
Points removed: 6
Total rows processed globally: 261808
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 11 rows after cleaning.
Trip max speed (2.07 m/s) is within the cap of 2.78 m/s.
Initial rows: 10
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 9
Points removed: 1
Total rows processed globally: 261817
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1101 rows after cleaning.
Trip max speed (57.08 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1100
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 47
Extreme outliers (>2x cap): 26
Very extreme outliers (>5x cap): 3
Rows after removal: 1073
Points removed: 27
Total rows processed globally: 262890
Outlier count before clipping: 64

Skipping field time: unsupported OGR type: 10

Data retained: 102 rows after cleaning.
Trip max speed (57.31 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 101
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 98
Points removed: 3
Total rows processed globally: 262988
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10
/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/scipy/signal/_signaltools.py:1563: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '

Data retained: 18 rows after cleaning.
Trip max speed (21.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 0
Rows after removal: 5
Points removed: 12
Total rows processed globally: 262993
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 84 rows after cleaning.
Trip max speed (13.49 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 83
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 81
Points removed: 2
Total rows processed globally: 263074
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 125 rows after cleaning.
Trip max speed (55.60 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 124
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 19
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 1
Rows after removal: 109
Points removed: 15
Total rows processed globally: 263183
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 567 rows after cleaning.
Trip max speed (64.98 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 566
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 52
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 557
Points removed: 9
Total rows processed globally: 263740
Outlier count before clipping: 60

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (3.00 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 12
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 263751
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 885 rows after cleaning.
Trip max speed (49.68 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 884
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 871
Points removed: 13
Total rows processed globally: 264622
Outlier count before clipping: 28

Skipping field time: unsupported OGR type: 10

Data retained: 81 rows after cleaning.
Trip max speed (51.04 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 80
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 76
Points removed: 4
Total rows processed globally: 264698
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 400 rows after cleaning.
Trip max speed (30.31 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 399
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 393
Points removed: 6
Total rows processed globally: 265091
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 30 rows after cleaning.
Trip max speed (14.43 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 29
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 26
Points removed: 3
Total rows processed globally: 265117
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (50.25 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 98
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 7
Rows after removal: 79
Points removed: 19
Total rows processed globally: 265196
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (77.87 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 12
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 10
Points removed: 2
Total rows processed globally: 265206
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (2.72 m/s) is within the cap of 6.94 m/s.
Initial rows: 33
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 32
Points removed: 1
Total rows processed globally: 265238
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 753 rows after cleaning.
Trip max speed (105.45 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 752
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 18
Very extreme outliers (>5x cap): 3
Rows after removal: 733
Points removed: 19
Total rows processed globally: 265971
Outlier count before clipping: 44

Skipping field time: unsupported OGR type: 10

Data retained: 322 rows after cleaning.
Trip max speed (67.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 321
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 316
Points removed: 5
Total rows processed globally: 266287
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (14.40 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 11
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 10
Points removed: 1
Total rows processed globally: 266297
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 110 rows after cleaning.
Trip max speed (3.52 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 109
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 108
Points removed: 1
Total rows processed globally: 266405
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 456 rows after cleaning.
Trip max speed (30.98 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 455
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 7
Rows after removal: 435
Points removed: 20
Total rows processed globally: 266840
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 2014 rows after cleaning.
Trip max speed (55.29 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 2013
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 136
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 0
Rows after removal: 1996
Points removed: 17
Total rows processed globally: 268836
Outlier count before clipping: 151

Skipping field time: unsupported OGR type: 10

Data retained: 389 rows after cleaning.
Trip max speed (22.56 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 388
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 383
Points removed: 5
Total rows processed globally: 269219
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 324 rows after cleaning.
Trip max speed (10.97 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 323
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 318
Points removed: 5
Total rows processed globally: 269537
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.59 m/s).
File Sub_Trajectories_Cleaned/20090703231838/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 188 rows after cleaning.
Trip max speed (2319.06 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 187
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 183
Points removed: 4
Total rows processed globally: 269720
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 623 rows after cleaning.
Trip max speed (164.47 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 622
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 2
Rows after removal: 609
Points removed: 13
Total rows processed globally: 270329
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 1148 rows after cleaning.
Trip max speed (122.76 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1147
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 200
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 3
Rows after removal: 1135
Points removed: 12
Total rows processed globally: 271464
Outlier count before clipping: 208

Skipping field time: unsupported OGR type: 10

Data retained: 710 rows after cleaning.
Trip max speed (29.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 709
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 3
Rows after removal: 694
Points removed: 15
Total rows processed globally: 272158
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 1113 rows after cleaning.
Trip max speed (110.79 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1112
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 3
Rows after removal: 1094
Points removed: 18
Total rows processed globally: 273252
Outlier count before clipping: 37

Skipping field time: unsupported OGR type: 10

Data retained: 195 rows after cleaning.
Trip max speed (228.61 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 194
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 190
Points removed: 4
Total rows processed globally: 273442
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 192 rows after cleaning.
Trip max speed (1816.64 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 191
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 52
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 3
Rows after removal: 174
Points removed: 17
Total rows processed globally: 273616
Outlier count before clipping: 57

Skipping field time: unsupported OGR type: 10

Data retained: 138 rows after cleaning.
Trip max speed (68.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 137
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 4
Rows after removal: 126
Points removed: 11
Total rows processed globally: 273742
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 491 rows after cleaning.
Trip max speed (113.79 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 490
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 41
Extreme outliers (>2x cap): 26
Very extreme outliers (>5x cap): 4
Rows after removal: 463
Points removed: 27
Total rows processed globally: 274205
Outlier count before clipping: 60

Skipping field time: unsupported OGR type: 10

Data retained: 135 rows after cleaning.
Trip max speed (17.50 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 134
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 13
Very extreme outliers (>5x cap): 2
Rows after removal: 120
Points removed: 14
Total rows processed globally: 274325
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 933 rows after cleaning.
Trip max speed (35.41 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 932
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 0
Rows after removal: 922
Points removed: 10
Total rows processed globally: 275247
Outlier count before clipping: 42

Skipping field time: unsupported OGR type: 10

Data retained: 219 rows after cleaning.
Trip max speed (26.08 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 218
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 211
Points removed: 7
Total rows processed globally: 275458
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 376 rows after cleaning.
Trip max speed (84.69 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 375
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 373
Points removed: 2
Total rows processed globally: 275831
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 137 rows after cleaning.
Trip max speed (27.27 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 136
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 129
Points removed: 7
Total rows processed globally: 275960
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 1895 rows after cleaning.
Trip max speed (70.62 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1894
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 173
Extreme outliers (>2x cap): 24
Very extreme outliers (>5x cap): 3
Rows after removal: 1869
Points removed: 25
Total rows processed globally: 277829
Outlier count before clipping: 192

Skipping field time: unsupported OGR type: 10

Data retained: 377 rows after cleaning.
Trip max speed (62.09 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 376
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 7
Rows after removal: 361
Points removed: 15
Total rows processed globally: 278190
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 155 rows after cleaning.
Trip max speed (211.78 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 154
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 51
Extreme outliers (>2x cap): 60
Very extreme outliers (>5x cap): 7
Rows after removal: 93
Points removed: 61
Total rows processed globally: 278283
Outlier count before clipping: 60

Skipping field time: unsupported OGR type: 10

Data retained: 102 rows after cleaning.
Trip max speed (16.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 101
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 98
Points removed: 3
Total rows processed globally: 278381
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 221 rows after cleaning.
Trip max speed (250.15 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 220
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 138
Very extreme outliers (>5x cap): 13
Rows after removal: 81
Points removed: 139
Total rows processed globally: 278462
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 27 rows after cleaning.
Trip max speed (2.97 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 26
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 25
Points removed: 1
Total rows processed globally: 278487
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 732 rows after cleaning.
Trip max speed (83.04 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 731
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 35
Extreme outliers (>2x cap): 23
Very extreme outliers (>5x cap): 4
Rows after removal: 707
Points removed: 24
Total rows processed globally: 279194
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 1404 rows after cleaning.
Trip max speed (78.67 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1403
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 933
Extreme outliers (>2x cap): 52
Very extreme outliers (>5x cap): 3
Rows after removal: 1350
Points removed: 53
Total rows processed globally: 280544
Outlier count before clipping: 945

Skipping field time: unsupported OGR type: 10

Data retained: 178 rows after cleaning.
Trip max speed (14.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 177
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 173
Points removed: 4
Total rows processed globally: 280717
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 564 rows after cleaning.
Trip max speed (57.06 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 563
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 2
Rows after removal: 559
Points removed: 4
Total rows processed globally: 281276
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 198 rows after cleaning.
Trip max speed (10.24 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 197
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 191
Points removed: 6
Total rows processed globally: 281467
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.39 m/s).
File Sub_Trajectories_Cleaned/20090514235037/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 12 rows after cleaning.
Trip max speed (109.14 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 11
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 9
Points removed: 2
Total rows processed globally: 281476
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20080908223454/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 782 rows after cleaning.
Trip max speed (270.90 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 781
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 775
Points removed: 6
Total rows processed globally: 282251
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 121 rows after cleaning.
Trip max speed (6.43 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 120
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 118
Points removed: 2
Total rows processed globally: 282369
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 13 rows after cleaning.
Trip max speed (0.94 m/s) is within the cap of 6.94 m/s.
Initial rows: 12
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 11
Points removed: 1
Total rows processed globally: 282380
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 114 rows after cleaning.
Trip max speed (11.91 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 113
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 112
Points removed: 1
Total rows processed globally: 282492
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 680 rows after cleaning.
Trip max speed (32.91 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 679
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 61
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 677
Points removed: 2
Total rows processed globally: 283169
Outlier count before clipping: 62

Skipping field time: unsupported OGR type: 10

Data retained: 182 rows after cleaning.
Trip max speed (524.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 181
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 4
Rows after removal: 161
Points removed: 20
Total rows processed globally: 283330
Outlier count before clipping: 49

Skipping field time: unsupported OGR type: 10

Data retained: 155 rows after cleaning.
Trip max speed (7.02 m/s) is within the cap of 11.11 m/s.
Initial rows: 154
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 153
Points removed: 1
Total rows processed globally: 283483
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (9 rows).
File Sub_Trajectories_Cleaned/20081115003759/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 1498 rows after cleaning.
Trip max speed (89.40 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1497
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 180
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 3
Rows after removal: 1477
Points removed: 20
Total rows processed globally: 284960
Outlier count before clipping: 189

Skipping field time: unsupported OGR type: 10

Data retained: 56 rows after cleaning.
Trip max speed (20.36 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 55
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 52
Points removed: 3
Total rows processed globally: 285012
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 85 rows after cleaning.
Trip max speed (430.89 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 84
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 3
Rows after removal: 80
Points removed: 4
Total rows processed globally: 285092
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 130 rows after cleaning.
Trip max speed (9.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 129
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 123
Points removed: 6
Total rows processed globally: 285215
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 567 rows after cleaning.
Trip max speed (31.92 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 566
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 560
Points removed: 6
Total rows processed globally: 285775
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 161 rows after cleaning.
Trip max speed (12.54 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 160
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 159
Points removed: 1
Total rows processed globally: 285934
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 161 rows after cleaning.
Trip max speed (15.44 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 160
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 154
Points removed: 6
Total rows processed globally: 286088
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 269 rows after cleaning.
Trip max speed (28.81 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 268
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 266
Points removed: 2
Total rows processed globally: 286354
Outlier count before clipping: 27

Skipping field time: unsupported OGR type: 10

Data retained: 616 rows after cleaning.
Trip max speed (27.82 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 615
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 1
Rows after removal: 603
Points removed: 12
Total rows processed globally: 286957
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 421 rows after cleaning.
Trip max speed (25.39 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 420
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 415
Points removed: 5
Total rows processed globally: 287372
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 91 rows after cleaning.
Trip max speed (18.35 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 90
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 86
Points removed: 4
Total rows processed globally: 287458
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 810 rows after cleaning.
Trip max speed (170.82 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 809
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 36
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 4
Rows after removal: 794
Points removed: 15
Total rows processed globally: 288252
Outlier count before clipping: 45

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20071006051353/bike_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 26 rows after cleaning.
Trip max speed (49.35 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 25
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 21
Points removed: 4
Total rows processed globally: 288273
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 349 rows after cleaning.
Trip max speed (39.43 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 348
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 2
Rows after removal: 341
Points removed: 7
Total rows processed globally: 288614
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 27 rows after cleaning.
Trip max speed (24.94 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 26
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 24
Points removed: 2
Total rows processed globally: 288638
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 498 rows after cleaning.
Trip max speed (95.45 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 497
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 491
Points removed: 6
Total rows processed globally: 289129
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 36 rows after cleaning.
Trip max speed (8657.10 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 35
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 33
Points removed: 2
Total rows processed globally: 289162
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 359 rows after cleaning.
Trip max speed (35.02 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 358
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 349
Points removed: 9
Total rows processed globally: 289511
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 792 rows after cleaning.
Trip max speed (116.66 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 791
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 160
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 782
Points removed: 9
Total rows processed globally: 290293
Outlier count before clipping: 166

Skipping field time: unsupported OGR type: 10

Data retained: 816 rows after cleaning.
Trip max speed (43.11 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 815
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 27
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 4
Rows after removal: 798
Points removed: 17
Total rows processed globally: 291091
Outlier count before clipping: 46

Skipping field time: unsupported OGR type: 10

Data retained: 398 rows after cleaning.
Trip max speed (135.24 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 397
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 33
Very extreme outliers (>5x cap): 5
Rows after removal: 363
Points removed: 34
Total rows processed globally: 291454
Outlier count before clipping: 55

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (123.78 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 20
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 16
Points removed: 4
Total rows processed globally: 291470
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 449 rows after cleaning.
Trip max speed (34.70 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 448
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 437
Points removed: 11
Total rows processed globally: 291907
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 286 rows after cleaning.
Trip max speed (39.09 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 285
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 283
Points removed: 2
Total rows processed globally: 292190
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 407 rows after cleaning.
Trip max speed (250.05 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 406
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 94
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 1
Rows after removal: 390
Points removed: 16
Total rows processed globally: 292580
Outlier count before clipping: 107

Skipping field time: unsupported OGR type: 10

Data retained: 1390 rows after cleaning.
Trip max speed (112.57 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 1389
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 33
Extreme outliers (>2x cap): 47
Very extreme outliers (>5x cap): 22
Rows after removal: 1341
Points removed: 48
Total rows processed globally: 293921
Outlier count before clipping: 76

Skipping field time: unsupported OGR type: 10

Data retained: 104 rows after cleaning.
Trip max speed (12.52 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 103
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 99
Points removed: 4
Total rows processed globally: 294020
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 330 rows after cleaning.
Trip max speed (32.15 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 329
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 2
Rows after removal: 317
Points removed: 12
Total rows processed globally: 294337
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 700 rows after cleaning.
Trip max speed (191.45 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 699
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 34
Extreme outliers (>2x cap): 23
Very extreme outliers (>5x cap): 5
Rows after removal: 675
Points removed: 24
Total rows processed globally: 295012
Outlier count before clipping: 52

Skipping field time: unsupported OGR type: 10

Data retained: 120 rows after cleaning.
Trip max speed (545.28 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 119
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 114
Points removed: 5
Total rows processed globally: 295126
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 326 rows after cleaning.
Trip max speed (46.04 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 325
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 123
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 320
Points removed: 5
Total rows processed globally: 295446
Outlier count before clipping: 124

Skipping field time: unsupported OGR type: 10

Data retained: 196 rows after cleaning.
Trip max speed (6.76 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 195
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 193
Points removed: 2
Total rows processed globally: 295639
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20090831234852/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 41 rows after cleaning.
Trip max speed (3.37 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 40
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 39
Points removed: 1
Total rows processed globally: 295678
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 229 rows after cleaning.
Trip max speed (189.25 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 228
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 3
Rows after removal: 221
Points removed: 7
Total rows processed globally: 295899
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 326 rows after cleaning.
Trip max speed (82.87 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 325
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 1
Rows after removal: 318
Points removed: 7
Total rows processed globally: 296217
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 328 rows after cleaning.
Trip max speed (99.13 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 327
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 5
Rows after removal: 319
Points removed: 8
Total rows processed globally: 296536
Outlier count before clipping: 23

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (19.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 16
Points removed: 6
Total rows processed globally: 296552
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 23 rows after cleaning.
Trip max speed (11.64 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 22
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 20
Points removed: 2
Total rows processed globally: 296572
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 120 rows after cleaning.
Trip max speed (9.26 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 119
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 118
Points removed: 1
Total rows processed globally: 296690
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 438 rows after cleaning.
Trip max speed (55.13 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 437
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 35
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 429
Points removed: 8
Total rows processed globally: 297119
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10

Data retained: 727 rows after cleaning.
Trip max speed (1019.69 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 726
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 25
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 12
Rows after removal: 708
Points removed: 18
Total rows processed globally: 297827
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (5 rows).
File Sub_Trajectories_Cleaned/20111207032835/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 66 rows after cleaning.
Trip max speed (5.55 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 65
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 64
Points removed: 1
Total rows processed globally: 297891
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 222 rows after cleaning.
Trip max speed (19.55 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 221
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 218
Points removed: 3
Total rows processed globally: 298109
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10
/Users/mac/.pyenv/versions/3.11.5/lib/python3.11/site-packages/scipy/signal/_signaltools.py:1563: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20080818083607/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 10 rows after cleaning.
Trip max speed (21.93 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 9
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 3
Points removed: 6
Total rows processed globally: 298112
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 59 rows after cleaning.
Trip max speed (20.96 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 58
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 54
Points removed: 4
Total rows processed globally: 298166
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 12 rows after cleaning.
Trip max speed (42.00 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 11
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 8
Points removed: 3
Total rows processed globally: 298174
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 402 rows after cleaning.
Trip max speed (64.38 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 401
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 39
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 8
Rows after removal: 386
Points removed: 15
Total rows processed globally: 298560
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 1422 rows after cleaning.
Trip max speed (195.07 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1421
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 65
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 1
Rows after removal: 1401
Points removed: 20
Total rows processed globally: 299961
Outlier count before clipping: 82

Skipping field time: unsupported OGR type: 10

Data retained: 210 rows after cleaning.
Trip max speed (85.31 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 209
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 202
Points removed: 7
Total rows processed globally: 300163
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20081202233433/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 686 rows after cleaning.
Trip max speed (55.51 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 685
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 46
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 0
Rows after removal: 672
Points removed: 13
Total rows processed globally: 300835
Outlier count before clipping: 57

Skipping field time: unsupported OGR type: 10

Data retained: 413 rows after cleaning.
Trip max speed (36.14 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 412
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 20
Extreme outliers (>2x cap): 16
Very extreme outliers (>5x cap): 7
Rows after removal: 395
Points removed: 17
Total rows processed globally: 301230
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10

Data retained: 427 rows after cleaning.
Trip max speed (54.63 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 426
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 24
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 415
Points removed: 11
Total rows processed globally: 301645
Outlier count before clipping: 31

Skipping field time: unsupported OGR type: 10

Data retained: 430 rows after cleaning.
Trip max speed (53.00 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 429
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 3
Rows after removal: 417
Points removed: 12
Total rows processed globally: 302062
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 49 rows after cleaning.
Trip max speed (2.36 m/s) is within the cap of 2.78 m/s.
Initial rows: 48
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 47
Points removed: 1
Total rows processed globally: 302109
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 976 rows after cleaning.
Trip max speed (37.92 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 975
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 140
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 966
Points removed: 9
Total rows processed globally: 303075
Outlier count before clipping: 147

Skipping field time: unsupported OGR type: 10

Data retained: 349 rows after cleaning.
Trip max speed (4617.07 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 348
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 342
Points removed: 6
Total rows processed globally: 303417
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 1104 rows after cleaning.
Trip max speed (78.13 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1103
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 150
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 1
Rows after removal: 1083
Points removed: 20
Total rows processed globally: 304500
Outlier count before clipping: 166

Skipping field time: unsupported OGR type: 10

Data retained: 101 rows after cleaning.
Trip max speed (15.99 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 100
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 99
Points removed: 1
Total rows processed globally: 304599
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (22.63 m/s).
File Sub_Trajectories_Cleaned/20080810013852/car_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 111 rows after cleaning.
Trip max speed (17.60 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 110
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 106
Points removed: 4
Total rows processed globally: 304705
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 227 rows after cleaning.
Trip max speed (53.19 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 226
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 115
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 218
Points removed: 8
Total rows processed globally: 304923
Outlier count before clipping: 119

Skipping field time: unsupported OGR type: 10

Data retained: 33 rows after cleaning.
Trip max speed (3.48 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 32
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 31
Points removed: 1
Total rows processed globally: 304954
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 249 rows after cleaning.
Trip max speed (202.10 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 248
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 169
Very extreme outliers (>5x cap): 19
Rows after removal: 78
Points removed: 170
Total rows processed globally: 305032
Outlier count before clipping: 18

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (4.02 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 20
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 19
Points removed: 1
Total rows processed globally: 305051
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 402 rows after cleaning.
Trip max speed (53.14 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 401
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 35
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 0
Rows after removal: 393
Points removed: 8
Total rows processed globally: 305444
Outlier count before clipping: 40

Skipping field time: unsupported OGR type: 10

Data retained: 96 rows after cleaning.
Trip max speed (32.46 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 95
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 93
Points removed: 2
Total rows processed globally: 305537
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 25 rows after cleaning.
Trip max speed (377.88 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 24
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 15
Points removed: 9
Total rows processed globally: 305552
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 78 rows after cleaning.
Trip max speed (91.62 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 77
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 72
Points removed: 5
Total rows processed globally: 305624
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 91 rows after cleaning.
Trip max speed (83.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 90
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 85
Points removed: 5
Total rows processed globally: 305709
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 1705 rows after cleaning.
Trip max speed (77.81 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1704
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 152
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 2
Rows after removal: 1688
Points removed: 16
Total rows processed globally: 307397
Outlier count before clipping: 164

Skipping field time: unsupported OGR type: 10

Data retained: 82 rows after cleaning.
Trip max speed (9.15 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 81
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 78
Points removed: 3
Total rows processed globally: 307475
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 600 rows after cleaning.
Trip max speed (123.52 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 599
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 17
Very extreme outliers (>5x cap): 6
Rows after removal: 581
Points removed: 18
Total rows processed globally: 308056
Outlier count before clipping: 37

Skipping field time: unsupported OGR type: 10

Data retained: 366 rows after cleaning.
Trip max speed (65.67 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 365
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 17
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 4
Rows after removal: 358
Points removed: 7
Total rows processed globally: 308414
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 408 rows after cleaning.
Trip max speed (49.01 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 407
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 401
Points removed: 6
Total rows processed globally: 308815
Outlier count before clipping: 19

Skipping field time: unsupported OGR type: 10

Data retained: 80 rows after cleaning.
Trip max speed (20.35 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 79
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 74
Points removed: 5
Total rows processed globally: 308889
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 321 rows after cleaning.
Trip max speed (43.65 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 320
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 314
Points removed: 6
Total rows processed globally: 309203
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 306 rows after cleaning.
Trip max speed (172.21 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 305
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 23
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 1
Rows after removal: 302
Points removed: 3
Total rows processed globally: 309505
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 64 rows after cleaning.
Trip max speed (17.93 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 63
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 61
Points removed: 2
Total rows processed globally: 309566
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 447 rows after cleaning.
Trip max speed (57.68 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 446
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 3
Rows after removal: 440
Points removed: 6
Total rows processed globally: 310006
Outlier count before clipping: 20

Skipping field time: unsupported OGR type: 10

Data retained: 80 rows after cleaning.
Trip max speed (1721.77 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 79
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 4
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 2
Rows after removal: 74
Points removed: 5
Total rows processed globally: 310080
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 496 rows after cleaning.
Trip max speed (43.03 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 495
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 11
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 486
Points removed: 9
Total rows processed globally: 310566
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10

Data retained: 876 rows after cleaning.
Trip max speed (243.13 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 875
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 103
Extreme outliers (>2x cap): 14
Very extreme outliers (>5x cap): 5
Rows after removal: 860
Points removed: 15
Total rows processed globally: 311426
Outlier count before clipping: 113

Skipping field time: unsupported OGR type: 10

Data retained: 27 rows after cleaning.
Trip max speed (3.97 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 26
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 25
Points removed: 1
Total rows processed globally: 311451
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 206 rows after cleaning.
Trip max speed (77.69 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 205
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 197
Points removed: 8
Total rows processed globally: 311648
Outlier count before clipping: 16

Skipping field time: unsupported OGR type: 10

Data retained: 474 rows after cleaning.
Trip max speed (343.89 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 473
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 89
Extreme outliers (>2x cap): 58
Very extreme outliers (>5x cap): 14
Rows after removal: 414
Points removed: 59
Total rows processed globally: 312062
Outlier count before clipping: 131

Skipping field time: unsupported OGR type: 10

Data retained: 620 rows after cleaning.
Trip max speed (55.15 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 619
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 617
Points removed: 2
Total rows processed globally: 312679
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 197 rows after cleaning.
Trip max speed (1466.24 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 196
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 191
Points removed: 5
Total rows processed globally: 312870
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 512 rows after cleaning.
Trip max speed (47.57 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 511
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 509
Points removed: 2
Total rows processed globally: 313379
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 299 rows after cleaning.
Trip max speed (13.79 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 298
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 292
Points removed: 6
Total rows processed globally: 313671
Outlier count before clipping: 32

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20071008080102/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 38 rows after cleaning.
Trip max speed (159.23 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 37
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 32
Points removed: 5
Total rows processed globally: 313703
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 32 rows after cleaning.
Trip max speed (64.94 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 31
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 28
Points removed: 3
Total rows processed globally: 313731
Outlier count before clipping: 7

Skipping field time: unsupported OGR type: 10

Data retained: 20 rows after cleaning.
Trip max speed (2.09 m/s) is within the cap of 2.78 m/s.
Initial rows: 19
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 18
Points removed: 1
Total rows processed globally: 313749
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 408 rows after cleaning.
Trip max speed (28.04 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 407
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 402
Points removed: 5
Total rows processed globally: 314151
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 499 rows after cleaning.
Trip max speed (184.02 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 498
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 2
Rows after removal: 487
Points removed: 11
Total rows processed globally: 314638
Outlier count before clipping: 31

Skipping field time: unsupported OGR type: 10

Data retained: 33 rows after cleaning.
Trip max speed (6.39 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 32
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 30
Points removed: 2
Total rows processed globally: 314668
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 99 rows after cleaning.
Trip max speed (16.24 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 98
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 97
Points removed: 1
Total rows processed globally: 314765
Outlier count before clipping: 22

Skipping field time: unsupported OGR type: 10

Data retained: 325 rows after cleaning.
Trip max speed (34.53 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 324
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 103
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 322
Points removed: 2
Total rows processed globally: 315087
Outlier count before clipping: 103

Skipping field time: unsupported OGR type: 10

Data retained: 127 rows after cleaning.
Trip max speed (7.12 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 126
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 7
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 122
Points removed: 4
Total rows processed globally: 315209
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10

Data retained: 1190 rows after cleaning.
Trip max speed (28.03 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1189
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 30
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 0
Rows after removal: 1179
Points removed: 10
Total rows processed globally: 316388
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10

Data retained: 41 rows after cleaning.
Trip max speed (5.20 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 40
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 39
Points removed: 1
Total rows processed globally: 316427
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 368 rows after cleaning.
Trip max speed (87.41 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 367
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 1
Rows after removal: 359
Points removed: 8
Total rows processed globally: 316786
Outlier count before clipping: 33

Skipping field time: unsupported OGR type: 10

Data retained: 15 rows after cleaning.
Trip max speed (3.61 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 14
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 13
Points removed: 1
Total rows processed globally: 316799
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 449 rows after cleaning.
Trip max speed (54.86 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 448
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 60
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 0
Rows after removal: 439
Points removed: 9
Total rows processed globally: 317238
Outlier count before clipping: 66

Skipping field time: unsupported OGR type: 10

Data retained: 229 rows after cleaning.
Trip max speed (278.10 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 228
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 33
Extreme outliers (>2x cap): 12
Very extreme outliers (>5x cap): 8
Rows after removal: 215
Points removed: 13
Total rows processed globally: 317453
Outlier count before clipping: 38

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (8 rows).
File Sub_Trajectories_Cleaned/20080922233154/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 175 rows after cleaning.
Trip max speed (36.53 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 174
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 26
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 2
Rows after removal: 164
Points removed: 10
Total rows processed globally: 317617
Outlier count before clipping: 31

Skipping field time: unsupported OGR type: 10

Data retained: 415 rows after cleaning.
Trip max speed (38.56 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 414
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 15
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 1
Rows after removal: 403
Points removed: 11
Total rows processed globally: 318020
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 37 rows after cleaning.
Trip max speed (4.90 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 36
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 35
Points removed: 1
Total rows processed globally: 318055
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20080301030756/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 355 rows after cleaning.
Trip max speed (38.38 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 354
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 32
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 350
Points removed: 4
Total rows processed globally: 318405
Outlier count before clipping: 35

Skipping field time: unsupported OGR type: 10

Data retained: 274 rows after cleaning.
Trip max speed (1681.72 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 273
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 3
Rows after removal: 264
Points removed: 9
Total rows processed globally: 318669
Outlier count before clipping: 21

Skipping field time: unsupported OGR type: 10

Data retained: 111 rows after cleaning.
Trip max speed (33.66 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 110
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 108
Points removed: 2
Total rows processed globally: 318777
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 21 rows after cleaning.
Trip max speed (2.66 m/s) is within the cap of 2.78 m/s.
Initial rows: 20
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 19
Points removed: 1
Total rows processed globally: 318796
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 38 rows after cleaning.
Trip max speed (13.66 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 37
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 33
Points removed: 4
Total rows processed globally: 318829
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20081206000403/subway_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 115 rows after cleaning.
Trip max speed (30.89 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 114
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 112
Points removed: 2
Total rows processed globally: 318941
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 314 rows after cleaning.
Trip max speed (46.62 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 313
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 153
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 0
Rows after removal: 308
Points removed: 5
Total rows processed globally: 319249
Outlier count before clipping: 157

Skipping field time: unsupported OGR type: 10

Data retained: 68 rows after cleaning.
Trip max speed (10.59 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 67
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 65
Points removed: 2
Total rows processed globally: 319314
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 621 rows after cleaning.
Trip max speed (71.67 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 620
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 21
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 6
Rows after removal: 609
Points removed: 11
Total rows processed globally: 319923
Outlier count before clipping: 30

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (22.07 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 33
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 1
Rows after removal: 31
Points removed: 2
Total rows processed globally: 319954
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 202 rows after cleaning.
Trip max speed (35.34 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 201
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 195
Points removed: 6
Total rows processed globally: 320149
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 64 rows after cleaning.
Trip max speed (3.78 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 63
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 62
Points removed: 1
Total rows processed globally: 320211
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 1936 rows after cleaning.
Trip max speed (41.88 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1935
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 266
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 0
Rows after removal: 1924
Points removed: 11
Total rows processed globally: 322135
Outlier count before clipping: 273

Skipping field time: unsupported OGR type: 10

Data retained: 283 rows after cleaning.
Trip max speed (312.26 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 282
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 2
Rows after removal: 279
Points removed: 3
Total rows processed globally: 322414
Outlier count before clipping: 5

Skipping field time: unsupported OGR type: 10

Data retained: 603 rows after cleaning.
Trip max speed (30.90 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 602
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 5
Extreme outliers (>2x cap): 6
Very extreme outliers (>5x cap): 0
Rows after removal: 595
Points removed: 7
Total rows processed globally: 323009
Outlier count before clipping: 25

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (6 rows).
File Sub_Trajectories_Cleaned/20080607035144/walk_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 85 rows after cleaning.
Trip max speed (177.87 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 84
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 22
Extreme outliers (>2x cap): 48
Very extreme outliers (>5x cap): 3
Rows after removal: 35
Points removed: 49
Total rows processed globally: 323044
Outlier count before clipping: 24

Skipping field time: unsupported OGR type: 10

Data retained: 237 rows after cleaning.
Trip max speed (77.49 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 236
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 47
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 1
Rows after removal: 231
Points removed: 5
Total rows processed globally: 323275
Outlier count before clipping: 48

Skipping field time: unsupported OGR type: 10

Data retained: 69 rows after cleaning.
Trip max speed (5.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 68
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 66
Points removed: 2
Total rows processed globally: 323341
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 34 rows after cleaning.
Trip max speed (96.30 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 33
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 20
Very extreme outliers (>5x cap): 4
Rows after removal: 12
Points removed: 21
Total rows processed globally: 323353
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 93 rows after cleaning.
Trip max speed (3.52 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 92
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 91
Points removed: 1
Total rows processed globally: 323444
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 18 rows after cleaning.
Trip max speed (12.21 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 17
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 16
Points removed: 1
Total rows processed globally: 323460
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 215 rows after cleaning.
Trip max speed (18.36 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 214
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 211
Points removed: 3
Total rows processed globally: 323671
Outlier count before clipping: 3

Skipping field time: unsupported OGR type: 10

Data retained: 57 rows after cleaning.
Trip max speed (5.80 m/s) is within the cap of 11.11 m/s.
Initial rows: 56
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 55
Points removed: 1
Total rows processed globally: 323726
Outlier count before clipping: 4

Skipping field time: unsupported OGR type: 10

Data retained: 66 rows after cleaning.
Trip max speed (13.41 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 65
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 13
Extreme outliers (>2x cap): 30
Very extreme outliers (>5x cap): 0
Rows after removal: 34
Points removed: 31
Total rows processed globally: 323760
Outlier count before clipping: 14

Skipping field time: unsupported OGR type: 10

Data retained: 354 rows after cleaning.
Trip max speed (19.72 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 353
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 2
Very extreme outliers (>5x cap): 0
Rows after removal: 350
Points removed: 3
Total rows processed globally: 324110
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 334 rows after cleaning.
Trip max speed (95.83 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 333
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 18
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 4
Rows after removal: 321
Points removed: 12
Total rows processed globally: 324431
Outlier count before clipping: 26

Skipping field time: unsupported OGR type: 10

Data retained: 549 rows after cleaning.
Trip max speed (27.08 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 548
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 42
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 546
Points removed: 2
Total rows processed globally: 324977
Outlier count before clipping: 42

Skipping field time: unsupported OGR type: 10

Data retained: 185 rows after cleaning.
Trip max speed (2.28 m/s) is within the cap of 2.78 m/s.
Initial rows: 184
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 183
Points removed: 1
Total rows processed globally: 325160
Outlier count before clipping: 1

Skipping field time: unsupported OGR type: 10

Data retained: 308 rows after cleaning.
Trip max speed (31.86 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 307
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 232
Extreme outliers (>2x cap): 50
Very extreme outliers (>5x cap): 7
Rows after removal: 256
Points removed: 51
Total rows processed globally: 325416
Outlier count before clipping: 235

Skipping field time: unsupported OGR type: 10

Data retained: 260 rows after cleaning.
Trip max speed (472.11 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 259
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 16
Extreme outliers (>2x cap): 156
Very extreme outliers (>5x cap): 8
Rows after removal: 102
Points removed: 157
Total rows processed globally: 325518
Outlier count before clipping: 29

Skipping field time: unsupported OGR type: 10

Data retained: 79 rows after cleaning.
Trip max speed (30.23 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 78
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 3
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 5
Rows after removal: 66
Points removed: 12
Total rows processed globally: 325584
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 153 rows after cleaning.
Trip max speed (42.16 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 152
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 0
Rows after removal: 148
Points removed: 4
Total rows processed globally: 325732
Outlier count before clipping: 11

Skipping field time: unsupported OGR type: 10

Data retained: 88 rows after cleaning.
Trip max speed (15.39 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 87
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 8
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 86
Points removed: 1
Total rows processed globally: 325818
Outlier count before clipping: 8

Skipping field time: unsupported OGR type: 10

Data retained: 118 rows after cleaning.
Trip max speed (947.81 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 117
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 4
Rows after removal: 112
Points removed: 5
Total rows processed globally: 325930
Outlier count before clipping: 9

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: insufficient rows (7 rows).
File Sub_Trajectories_Cleaned/20111021143338/bus_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 873 rows after cleaning.
Trip max speed (98.65 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 872
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 19
Very extreme outliers (>5x cap): 3
Rows after removal: 852
Points removed: 20
Total rows processed globally: 326782
Outlier count before clipping: 43

Skipping field time: unsupported OGR type: 10

Data retained: 1303 rows after cleaning.
Trip max speed (43.16 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1302
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 69
Extreme outliers (>2x cap): 15
Very extreme outliers (>5x cap): 0
Rows after removal: 1286
Points removed: 16
Total rows processed globally: 328068
Outlier count before clipping: 81

Skipping field time: unsupported OGR type: 10

Data retained: 434 rows after cleaning.
Trip max speed (4589.67 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 433
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 14
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 1
Rows after removal: 427
Points removed: 6
Total rows processed globally: 328495
Outlier count before clipping: 17

Skipping field time: unsupported OGR type: 10

Data retained: 1937 rows after cleaning.
Trip max speed (129.90 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1936
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 221
Extreme outliers (>2x cap): 10
Very extreme outliers (>5x cap): 1
Rows after removal: 1925
Points removed: 11
Total rows processed globally: 330420
Outlier count before clipping: 228

Skipping field time: unsupported OGR type: 10

Data retained: 319 rows after cleaning.
Trip max speed (6106.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 318
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 31
Extreme outliers (>2x cap): 11
Very extreme outliers (>5x cap): 4
Rows after removal: 306
Points removed: 12
Total rows processed globally: 330726
Outlier count before clipping: 41

Skipping field time: unsupported OGR type: 10

Data retained: 1234 rows after cleaning.
Trip max speed (1119.88 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1233
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 111
Extreme outliers (>2x cap): 854
Very extreme outliers (>5x cap): 35
Rows after removal: 378
Points removed: 855
Total rows processed globally: 331104
Outlier count before clipping: 139

Skipping field time: unsupported OGR type: 10

Data retained: 127 rows after cleaning.
Trip max speed (771.95 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 126
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 2
Extreme outliers (>2x cap): 4
Very extreme outliers (>5x cap): 3
Rows after removal: 121
Points removed: 5
Total rows processed globally: 331225
Outlier count before clipping: 6

Skipping field time: unsupported OGR type: 10

Data retained: 1426 rows after cleaning.
Trip max speed (39.42 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1425
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 150
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 0
Rows after removal: 1415
Points removed: 10
Total rows processed globally: 332640
Outlier count before clipping: 155

Skipping field time: unsupported OGR type: 10

Data retained: 217 rows after cleaning.
Trip max speed (16.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 216
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 10
Extreme outliers (>2x cap): 8
Very extreme outliers (>5x cap): 1
Rows after removal: 207
Points removed: 9
Total rows processed globally: 332847
Outlier count before clipping: 15

Skipping field time: unsupported OGR type: 10

Data retained: 728 rows after cleaning.
Trip max speed (44.58 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 727
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 79
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 0
Rows after removal: 721
Points removed: 6
Total rows processed globally: 333568
Outlier count before clipping: 83

Skipping field time: unsupported OGR type: 10

Data retained: 125 rows after cleaning.
Trip max speed (76.88 m/s) exceeds the cap of 13.89 m/s.
Initial rows: 124
Speed cap: 13.89
Regular capped (cap < speed <= 2x cap): 12
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 120
Points removed: 4
Total rows processed globally: 333688
Outlier count before clipping: 13

Skipping field time: unsupported OGR type: 10

Data retained: 1804 rows after cleaning.
Trip max speed (14.83 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 1803
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 1
Very extreme outliers (>5x cap): 0
Rows after removal: 1801
Points removed: 2
Total rows processed globally: 335489
Outlier count before clipping: 36

Skipping field time: unsupported OGR type: 10

Data retained: 82 rows after cleaning.
Trip max speed (149.29 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 81
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 6
Extreme outliers (>2x cap): 7
Very extreme outliers (>5x cap): 3
Rows after removal: 73
Points removed: 8
Total rows processed globally: 335562
Outlier count before clipping: 10

Skipping field time: unsupported OGR type: 10

Data retained: 229 rows after cleaning.
Trip max speed (93.80 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 228
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 9
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 224
Points removed: 4
Total rows processed globally: 335786
Outlier count before clipping: 12

Skipping field time: unsupported OGR type: 10

Data retained: 14 rows after cleaning.
Trip max speed (2.38 m/s) is within the cap of 2.78 m/s.
Initial rows: 13
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 0
Very extreme outliers (>5x cap): 0
Rows after removal: 12
Points removed: 1
Total rows processed globally: 335798
Outlier count before clipping: 0

Skipping field time: unsupported OGR type: 10

Data retained: 364 rows after cleaning.
Trip max speed (38.89 m/s) exceeds the cap of 6.94 m/s.
Initial rows: 363
Speed cap: 6.94
Regular capped (cap < speed <= 2x cap): 29
Extreme outliers (>2x cap): 9
Very extreme outliers (>5x cap): 3
Rows after removal: 353
Points removed: 10
Total rows processed globally: 336151
Outlier count before clipping: 36

Skipping field time: unsupported OGR type: 10

Data retained: 1341 rows after cleaning.
Trip max speed (86.46 m/s) exceeds the cap of 11.11 m/s.
Initial rows: 1340
Speed cap: 11.11
Regular capped (cap < speed <= 2x cap): 817
Extreme outliers (>2x cap): 35
Very extreme outliers (>5x cap): 6
Rows after removal: 1304
Points removed: 36
Total rows processed globally: 337455
Outlier count before clipping: 825

Skipping field time: unsupported OGR type: 10
Skipping field time: unsupported OGR type: 10

Data discarded: mean speed too high (16.98 m/s).
File Sub_Trajectories_Cleaned/20080430235534/train_cleaned.geojson did not pass cleaning. Skipping.
Data retained: 223 rows after cleaning.
Trip max speed (15.60 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 222
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 0
Extreme outliers (>2x cap): 3
Very extreme outliers (>5x cap): 1
Rows after removal: 218
Points removed: 4
Total rows processed globally: 337673
Outlier count before clipping: 2

Skipping field time: unsupported OGR type: 10

Data retained: 24 rows after cleaning.
Trip max speed (29.80 m/s) exceeds the cap of 2.78 m/s.
Initial rows: 23
Speed cap: 2.78
Regular capped (cap < speed <= 2x cap): 1
Extreme outliers (>2x cap): 5
Very extreme outliers (>5x cap): 2
Rows after removal: 17
Points removed: 6
Total rows processed globally: 337690
Outlier count before clipping: 4
Trip-level dataset shape: (1021, 25)

,total_distance,max_speed,min_speed,speed_std,avg_speed,avg_acceleration,max_acceleration,acceleration_std,num_turns,turn_rate,...,end_time,duration_sec,transport_mode,initial_points,points_removed,pct_points_removed,regular_capped_points,extreme_outliers_removed,speed_cap,trip_summary
0,0.056625,6.202274,1.608878,1.734081,3.870224,0.013033,0.074890,0.047354,0,0.000000,...,2008-11-03 11:02:51,45.0,subway,9,1,11.111111,0,0,6.94,\nTrip Summary:\n- Start: 2008-11-03 11:02:06 ...
1,6.241616,10.008000,0.123001,2.180204,3.425304,0.002405,0.655239,0.068961,454,4.938361,...,2008-11-03 14:35:06,5660.0,walk,824,29,3.519417,30,28,2.78,\nTrip Summary:\n- Start: 2008-11-03 13:00:46 ...
2,3.788475,15.398024,2.016791,3.263822,10.277240,-0.002750,0.022441,0.017267,3,0.122117,...,2008-03-14 09:29:58,1475.0,bike,23,1,4.347826,3,0,6.94,\nTrip Summary:\n- Start: 2008-03-14 09:05:23 ...
3,0.897731,4.839679,0.896842,1.078303,4.320466,0.000126,0.004599,0.002624,6,0.456274,...,2008-03-14 10:48:33,822.0,walk,15,1,6.666667,0,0,2.78,\nTrip Summary:\n- Start: 2008-03-14 10:34:51 ...
4,1.574620,21.707923,1.998040,2.555151,13.062219,-0.005701,0.890108,0.232416,11,1.666667,...,2008-08-02 16:07:55,404.0,bike,186,5,2.688172,5,4,6.94,\nTrip Summary:\n- Start: 2008-08-02 16:01:11 ...

Trip-level data saved to 'trip_level_data.csv'.
Enhanced cleaning analysis saved to 'ML_result/capping_analysis.txt'.

In [ ]:
# import os
# import glob
# import geopandas as gpd
# import pandas as pd
# import warnings
# warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

# # Folder where the cleaned sub-trajectories are stored.
# folder_path = "Sub_Trajectories_Cleaned"
# geojson_files = glob.glob(os.path.join(folder_path, "**/*.geojson"), recursive=True)
# print(f"Number of GeoJSON files found: {len(geojson_files)}")

# # List to store trip-level metrics
# trip_data = []

# for file in geojson_files:
#     try:
#         # Read the file into a GeoDataFrame.
#         gdf = gpd.read_file(file)
#         if gdf.empty:
#             print(f"File {file} is empty. Skipping.")
#             continue

#         # Clean the trajectory using your function.
#         gdf_clean = clean_trajectory(gdf)
#         if gdf_clean.empty:
#             print(f"File {file} did not pass cleaning. Skipping.")
#             continue

#         # Ensure time differences are computed.
#         gdf_clean = calculate_time_differences_manually(gdf_clean)
#         # Ensure datetime is properly parsed and sorted.
#         if not pd.api.types.is_datetime64_any_dtype(gdf_clean['datetime']):
#             gdf_clean['datetime'] = pd.to_datetime(gdf_clean['datetime'])
#         gdf_clean = gdf_clean.sort_values('datetime').reset_index(drop=True)

#         # Compute enriched (trip-level) metrics.
#         metrics = compute_enriched_metrics(gdf_clean)
#         if metrics is None:
#             print(f"Metrics could not be computed for file {file}. Skipping.")
#             continue

#         # Calculate additional trip-level information.
#         start_time = gdf_clean['datetime'].iloc[0]
#         end_time = gdf_clean['datetime'].iloc[-1]
#         duration_sec = (end_time - start_time).total_seconds()

#         # Determine overall transport mode:
#         if 'transport_mode' in gdf_clean.columns:
#             mode_series = gdf_clean['transport_mode'].dropna()
#             if len(mode_series.unique()) == 1:
#                 trip_mode = mode_series.iloc[0]
#             else:
#                 trip_mode = mode_series.mode()[0]
#         else:
#             trip_mode = "Unknown"

#         # Optionally, generate a human-readable trip summary.
#         summary, _ = generate_trip_description(gdf_clean, metrics)

#         # Add extra fields to the metrics dictionary.
#         metrics['trip_id'] = os.path.basename(file)
#         metrics['start_time'] = start_time
#         metrics['end_time'] = end_time
#         metrics['duration_sec'] = duration_sec
#         metrics['transport_mode'] = trip_mode
#         metrics['trip_summary'] = summary

#         trip_data.append(metrics)

#     except Exception as e:
#         print(f"Error processing file {file}: {e}")

# # Create a DataFrame from the aggregated trip metrics.
# df_trip_level = pd.DataFrame(trip_data)
# print("Trip-level dataset shape:", df_trip_level.shape)
# display(df_trip_level.head())

# # Save the aggregated trip-level dataset to CSV.
# output_csv = "trip_level_data.csv"
# df_trip_level.to_csv(output_csv, index=False)
# print(f"Trip-level data saved to '{output_csv}'.")

Skipping field time: unsupported OGR type: 10

Number of GeoJSON files found: 1096
Data retained: 15 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
Name: speed, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 900 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
895    0.0
896    0.0
897    0.0
898    0.0
899    0.0
Name: speed, Length: 900, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 28 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
Name: speed, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 16 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
Name: speed, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 206 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
201    0.0
202    0.0
203    0.0
204    0.0
205    0.0
Name: speed, Length: 206, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 223 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 11.11 m/s.
Speed cap: 11.11
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
218    0.0
219    0.0
220    0.0
221    0.0
222    0.0
Name: speed, Length: 223, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 530 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 13.89 m/s.
Speed cap: 13.89
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
525    0.0
526    0.0
527    0.0
528    0.0
529    0.0
Name: speed, Length: 530, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 245 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
240    0.0
241    0.0
242    0.0
243    0.0
244    0.0
Name: speed, Length: 245, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 76 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 11.11 m/s.
Speed cap: 11.11
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
     ...
71    0.0
72    0.0
73    0.0
74    0.0
75    0.0
Name: speed, Length: 76, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 308 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
303    0.0
304    0.0
305    0.0
306    0.0
307    0.0
Name: speed, Length: 308, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 39 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 11.11 m/s.
Speed cap: 11.11
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
30    0.0
31    0.0
32    0.0
33    0.0
34    0.0
35    0.0
36    0.0
37    0.0
38    0.0
Name: speed, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 62 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
     ...
57    0.0
58    0.0
59    0.0
60    0.0
61    0.0
Name: speed, Length: 62, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 850 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
845    0.0
846    0.0
847    0.0
848    0.0
849    0.0
Name: speed, Length: 850, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 91 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
     ...
86    0.0
87    0.0
88    0.0
89    0.0
90    0.0
Name: speed, Length: 91, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 24 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
Name: speed, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 394 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
389    0.0
390    0.0
391    0.0
392    0.0
393    0.0
Name: speed, Length: 394, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 63 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 2.78 m/s.
Speed cap: 2.78
Speed: 0     NaN
1     0.0
2     0.0
3     0.0
4     0.0
     ...
58    0.0
59    0.0
60    0.0
61    0.0
62    0.0
Name: speed, Length: 63, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 568 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 6.94 m/s.
Speed cap: 6.94
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
563    0.0
564    0.0
565    0.0
566    0.0
567    0.0
Name: speed, Length: 568, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0

Skipping field time: unsupported OGR type: 10

Data retained: 698 rows after cleaning.
Trip max speed (0.00 m/s) is within the cap of 11.11 m/s.
Speed cap: 11.11
Speed: 0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
693    0.0
694    0.0
695    0.0
696    0.0
697    0.0
Name: speed, Length: 698, dtype: float64
rows_exceed_mode: 0
mode_capped_rows_global: 0
Trip-level dataset shape: (19, 19)

,total_distance,max_speed,min_speed,speed_std,avg_speed,avg_acceleration,max_acceleration,acceleration_std,num_turns,turn_rate,avg_turn_angle,turn_angle_std,avg_bearing_change,trip_id,start_time,end_time,duration_sec,transport_mode,trip_summary
0,0.099576,6.804614,0.0,2.175556,4.548674,0.007313,0.128242,0.075961,3,2.769231,44.343175,58.642820,44.343175,subway_cleaned.geojson,2008-11-03 11:01:56,2008-11-03 11:03:06,70.0,subway,\nTrip Summary:\n- Start: 2008-11-03 11:01:56 ...
1,7.335194,10.008000,0.0,2.491312,3.861793,0.002583,0.655239,0.076420,492,5.210944,52.426213,49.501440,52.426213,walk_cleaned.geojson,2008-11-03 13:00:41,2008-11-03 14:35:11,5670.0,walk,\nTrip Summary:\n- Start: 2008-11-03 13:00:41 ...
2,4.270492,24.984000,0.0,4.170243,9.485650,0.004165,0.144995,0.029646,6,0.223602,22.217181,33.085706,22.217181,bike_cleaned.geojson,2008-03-14 09:03:40,2008-03-14 09:31:28,1668.0,bike,\nTrip Summary:\n- Start: 2008-03-14 09:03:40 ...
3,1.028568,5.929675,0.0,1.576715,4.152453,-0.000010,0.007549,0.004052,8,0.561404,46.821988,42.737292,46.821988,walk_cleaned.geojson,2008-03-14 10:34:18,2008-03-14 10:48:47,869.0,walk,\nTrip Summary:\n- Start: 2008-03-14 10:34:18 ...
4,1.682420,22.198744,0.0,3.230470,13.281676,-0.004001,1.237699,0.248023,18,2.583732,14.340835,19.533411,14.340835,bike_cleaned.geojson,2008-08-02 16:00:57,2008-08-02 16:07:57,420.0,bike,\nTrip Summary:\n- Start: 2008-08-02 16:00:57 ...

Trip-level data saved to 'trip_level_data.csv'.
Capping analysis saved to 'ML_result/capping_analysis.txt'.